### ISSUE TITLE
Faster RCNN finue-tuned for COCO?

### ISSUE THREAD

**Issue by guyrose3** [rbgirshick/py-faster-rcnn#101]
Hi, Is there an available weight file for faster-rcnn fine-tuned on COCO object detections?
The prototxt files and the solver are currently available, but not the weights.
If not, is there one for fast-rcnn?

**Comment by rbgirshick** [comment]
I'm planning on releasing a trained model soon (< 1 week).

**Comment by guyrose3** [comment]
Thanks!

**Comment by rbgirshick** [comment]
I've posted a model. Please see https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/README.md for details.

**Comment by haria** [comment]
Hi @rbgirshick thank you for release the model for mscoco dataset, when i try your model by using tools/demo.py I found the output label is not correct, I think the CLASSES should be adapt for mscoco dataset respectively, could you please share category info with me? thank you in advance!
CLASSES = ('__background__',
           'aeroplane', 'bicycle', 'bird', 'boat',
           'bottle', 'bus', 'car', 'cat', 'chair',
           'cow', 'diningtable', 'dog', 'horse',
           'motorbike', 'person', 'pottedplant',
           'sheep', 'sofa', 'train', 'tvmonitor')

**Comment by liuchang8am** [comment]
@haria check this out
CLASSES = ('__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus','train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter’,'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack','umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite','baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl','banana', 'apple', 'sandwich', 'orange', 'broccoli','carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table','toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven','toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier','toothbrush')

**Comment by sidgan** [comment]
Hi, 

The link (https://eecs.berkeley.edu/~rbg/faster-rcnn-data/coco_vgg16_faster_rcnn_final.caffemodel) to the caffemodel file as described in the README (https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/README.md) does not work. 

@rbgirshick Could you please update the link.

**Comment by monajalal** [comment]
@rbgirshick I get "Page Not Found" when browsing to www.cs.berkeley.edu/~rbg/faster-rcnn-data/coco_vgg16_faster_rcnn_final.caffemodel
Can you please fix that?

**Comment by sidgan** [comment]
If you do:

` wget www.cs.berkeley.edu/~rbg/faster-rcnn-data/coco_vgg16_faster_rcnn_final.caffemodel
`
it works!

**Comment by bitwangdan** [comment]
@liuchang8am what should i change the prototxt variable in demo.py?
prototxt = os.path.join(cfg.MODELS_DIR, NETS[args.demo_net][0],
                            'faster_rcnn_alt_opt', 'faster_rcnn_test.pt')
