### ISSUE TITLE
gitignore some autogenerated files?

### ISSUE THREAD

**Issue by forresti** [rbgirshick/py-faster-rcnn#102]
I believe the following files are autogenerated by Cython:

    lib/pycocotools/_mask.so
    lib/pycocotools/_mask.c

Perhaps these belong in `.gitignore`?

Probably too small of an issue to be worth the overhead making a PR, since it'd just be a two-line change.

**Comment by moskewcz** [comment]
yep, i was just going to comment on the already-closed #99 to this effect. but a new issue is probably better anyway! the usual .gitignore of:
    *.c
    *.so
used in other such dirs is fine i'd guess.

**Comment by rbgirshick** [comment]
Oops, should have ignored these in #99. Fixed in commit 8ff49d3. Thanks!
