### ISSUE TITLE
running demo with pretrained imagenet model

### ISSUE THREAD

**Issue by jorgyz** [rbgirshick/py-faster-rcnn#106]
Has anyone been able to successfully adapt the demo.py to use the imagenet models?  I downloaded the models, as instructed by the readme, and then modified demo.py, setting classes to the 1000 imagenet classes and adjusting the path to the caffemodel file. I'm using the prototxt file from models/pascal_voc/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt with num_output=1001 in "cls_score" layer and num_output=4004 in "bbox_pred" layer.  When I run the script, it completes without errors, but nothing is detected in any of the images I have tried (even when setting CONF_THRESH=0.01).
Any idea what I'm missing?

**Comment by happyharrycn** [comment]
Notice the model used for ImageNet classification (1000 classes) is not applicable for detection tasks. I did not know anyone had released a detection model for ImageNet Det. When you plug in a model for classification, all the "detection" layers are filled with random weights (or zeros). And that is why you can not get meaningful results.

**Comment by jorgyz** [comment]
Thanks for clearing up my misunderstanding. I was thrown off by the mention of downloading the ImageNet models in the readme.
