### ISSUE TITLE
How to use the multi-gpu to train faster-rcnn?

### ISSUE THREAD

**Issue by banxiaduhuo** [rbgirshick/py-faster-rcnn#107]
The new version of Caffe has supported multi-gpu. If I want to train faster-rcnn with multi-gpu, how should I do?

**Comment by rbgirshick** [comment]
Sadly you can't use multi-gpu training. The issue is that py-faster-rcnn makes heavy use of python layers and python layers break the multi-gpu feature.

**Comment by liangzimei** [comment]
It  means fast-rcnn also can't use multi-gpu to train, right? @rbgirshick

**Comment by bharatsingh430** [comment]
https://github.com/bharatsingh430/py-R-FCN-multiGPU/

you can use this branch, for multi-gpu
