### ISSUE TITLE
Why is my faster-rcnn with ZF slower than with vgg16?

### ISSUE THREAD

**Issue by JohnnyY8** [rbgirshick/py-faster-rcnn#108]
I have run demo.py according to the instructions. But there is some strange problems about running time, the faster-rcnn with ZF is slower than with vgg16? I do not know what happened? Does anyone can help me?
The results are following:
![image](https://cloud.githubusercontent.com/assets/12611573/13659695/d03d5696-e6be-11e5-8ab0-18beada162a0.png)
![image](https://cloud.githubusercontent.com/assets/12611573/13659717/f4968968-e6be-11e5-8e85-31bde73d45ab.png)

**Comment by Oh233** [comment]
I guess you make caffe with cudnn? If so, try to make again without cudnn and test the speed.

**Comment by JohnnyY8** [comment]
Thank you for your solution! @Oh233   It does works!
I still have a question, the paper about "faster r-cnn" said the frame rate of 17fps with ZF, but the results I got are about 10fps. It is still a large distance. Could you please help me?

**Comment by chrert** [comment]
So the ZF model is actually slower if caffe was compiled with cudnn? Shouldn't cudnn speed up things?
@Oh233 Do you know the reason for that?

**Comment by Oh233** [comment]
@JohnnyY8 Python implementation will be slower, as described in the author's README. And it may also be affected by GPU and CPU. So sorry I could not give a exactly answer to this issue.

@chrert That's weird. I didn't found reason for that yet.

**Comment by JohnnyY8** [comment]
It is ok, still thanks for everything! @Oh233  Your answer is really helpful for me!
And I am curious about how did you find the cudnn slow down the ZF model?

**Comment by Oh233** [comment]
@JohnnyY8 Well, at the very beginning, caffe-fast-rcnn didn't support cudnn (if I remembered correctly). At that time the speed is as my expected. But after one day I built with cudnn and it becomes very slow. Then I found this problem.

**Comment by JohnnyY8** [comment]
WOO, I see. I really think about the problem result from cudnn. 
谢谢！ @Oh233

**Comment by JohnnyY8** [comment]
WOO, I see. I really do not think about the problem result from cudnn. 
谢谢！ @Oh233

**Comment by JohnnyY8** [comment]
WOO, I see. I really do not think about the problem result from cudnn before. 
谢谢！ @Oh233

**Comment by rbgirshick** [comment]
This commit fixes the problem with ZF when using CUDNN: 96dc9f1. For some reason the LRN layers are very slow with CUDNN. As for fps, as pointed out the Python implementation is a little slower due to some ops happening on CPU also you may not be using the same GPU (or clockspeed configuration).
