### ISSUE TITLE
The problems about FCs ?

### ISSUE THREAD

**Issue by JohnnyY8** [rbgirshick/py-faster-rcnn#111]
There follows a picture in the "Fast RCNN", I hava some problems about the fc layers. For the two "FCS" behind the "ROI pooling layer", are they orginally one fc layer and then divided into these two small "FCs" according to the "Truncated SVD" that mentioned in paper? How to divid it concretely?
![20160311101531](https://cloud.githubusercontent.com/assets/12611573/13691276/7e5da8f8-e772-11e5-8a03-64ab03fb8f54.jpg)

**Comment by happyharrycn** [comment]
There are two Fully Connected layers (FCs) in VGG16/ZF/Caffe net. You can apply the SVD trick to divide each FC into two smaller FCs. The actually implementation can be found in ./tools/compress_net.py

**Comment by JohnnyY8** [comment]
OK, I have seen the function "compress_weight". It is clear. Thank you so much for the solution for my three problems! @happyharrycn
