### ISSUE TITLE
Segmentation fault when running ./demo.sh on GPU

### ISSUE THREAD

**Issue by davidkh1** [rbgirshick/py-faster-rcnn#119]
I can run the demo successfully in CPU mode (`./tools/demo.py --cpu`), but receive segmentation fault in GPU mode.

When I run:
`./tools/demo.py`
The last line is 

> Segmentation fault

which happens in test.py file, in line  `blobs_out = net.forward(**forward_kwargs)`
I can run `demo.py` with debugger and can't spot any issue. There is no spike in GPU or CPU usage as well.
Configuration: NVidia 980, 4G, RAM: 16G, Ubuntu 14.04, CUDA 7.5, cuDNN v4

Has anyone run into the same problem?
Thanks!

**Comment by davidkh1** [comment]
Just solved it by downgrading cuDNN v4 to cuDNN v3.

**Comment by briantse100** [comment]
i have encountered this issue and have solved it by copying the all cudnn file in the src/caffe/layers in the latest version caffe to the caffe-fast-rcnn.
