### ISSUE TITLE
can I train the model from 'Stage 1 RPN, generate proposals' ?

### ISSUE THREAD

**Issue by sunshineatnoon** [rbgirshick/py-faster-rcnn#13]
I am training the model on ImageNet and already finished stage 1, I have `zf_rpn_stage1_iter_80000.caffemodel` and `zf_rpn_stage1_iter_80000_proposals.pkl` in my `output/faster_rcnn_alt_opt/train/` folder. But then I encountered this error:
```
File "/home/Documents/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 100, in _sample_rois
    fg_inds, size=fg_rois_per_this_image, replace=False)
  File "mtrand.pyx", line 1070, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:8044)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```
So the training stacked. After fixing this error, can I start training from the next stage directly? I don't want to do the 80000 iterations from the `Stage 1 RPN, init from ImageNet model` stage again.

**Comment by fengyuxi55** [comment]
@sunshineatnoon Hi, can you tell me how to fix this issue?

**Comment by sunshineatnoon** [comment]
@fengyuxi55 This error was caused by the `npr.choice function`, I just modified it like this:
```
    if fg_inds.size > 0:
    	for i in range(0,len(fg_inds)):
    		fg_inds[i] = int(fg_inds[i])
        fg_inds = npr.choice(fg_inds, size=int(fg_rois_per_this_image), replace=False)
```
Notice there are two `npr.choice`, so you need to modify them all.
As to train from `Stage 1 RPN, generate proposals`, I tried to pickle things and restart training from the next stage, but unfortunately, I didn't get a good model by doing so, now I have to train the whole model again.

**Comment by fengyuxi55** [comment]
@sunshineatnoon , Thanks for help, I did it and it works!

**Comment by athus1990** [comment]
I tried this solution,however I end up getting this error:
  File "/usr/local/PYFASTER2/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 126, in _sample_rois
    labels[fg_rois_per_this_image:] = 0
IndexError: failed to coerce slice entry of type numpy.float64 to integer


what is causing this issue?

**Comment by Sundrops** [comment]
After i modify two npr.choice(), this error also occurs. Finally I solve it by this way,
as below:
Note that float indexes will not error in Numpy 1.11, we reverted that to allow more time for downstream projects to adjust. There has been a deprecation warning out for ~1.5 years, and the error will return in 1.12.

**Comment by junwenchen** [comment]
@ @Sundrops  I have encountered the same problem. So you mean you uninstalled numpy1.12 and reinstalled numpy1.11? Am I correct? Thanks a lot

**Comment by Sundrops** [comment]
@junwenchen yeah! you can have a try.

**Comment by junwenchen** [comment]
@Sundrops all right. thank you

**Comment by xingweiXu** [comment]
@sunshineatnoon I encountered all the same problems. Now I have fixed them. I want to know how to resuming training from  zf_rpn_stage1_iter_80000.caffemodel. Would you like to paste the command line? I know it is too long time to recall the work. Thanks

**Comment by ACcrystal** [comment]
@xingweiXu I also encountered the same problem.So,Have you find any solution to solve this problem?Thank you a lot.

**Comment by nanzhixiong** [comment]
@sunshineatnoon  @fengyuxi55 @ how to find npr.choice function?

**Comment by nanzhixiong** [comment]
@Sundrops if use sudo pip install -U numpy==1.11.0, the following error occurs: ImportError: numpy.core.multiarray failed to import.  to remove the error, sudo pip install -U numpy is needed. it result in that the numpy changes.

**Comment by hanna-kim** [comment]
@nanzhixiong  I have same problem. Have you solved it? Thank you.
