### ISSUE TITLE
Just want to use 200 object detection. 

### ISSUE THREAD

**Issue by apple2373** [rbgirshick/py-faster-rcnn#139]
Hi, 

I was able to run demo.py which detects 20 classes with region.  I just want to get 200 object classes (or more if possible) with regions. How can I do that? Is the pre-trained model available?  I am aware of the section "Download pre-trained ImageNet models" in readme, but I am not sure how to use it. 

Best,
Satoshi

**Comment by dkislyuk** [comment]
I would recommend taking a look at https://github.com/coldmanck/fast-rcnn/blob/master/README.md, which has detailed instructions on how to use `py-faster-rcnn` with a custom dataset.

**Comment by apple2373** [comment]
Thank you. I did not plan to train by myself, but the information is still useful.

**Comment by micros-uav** [comment]
I also want to know how to use "Download pre-trained ImageNet models"
