### ISSUE TITLE
PyFPE_jbuf error while running demo.py

### ISSUE THREAD

**Issue by chaitu2289** [rbgirshick/py-faster-rcnn#14]
I have installed and compiled all the prerequisites and I am getting following error while running 
./tools/demo.py.  

Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/path/to/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/path/to/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.cpu_nms import cpu_nms
ImportError: /path/to/py-faster-rcnn/tools/../lib/nms/cpu_nms.so: undefined symbol: PyFPE_jbuf

cpu_nms.so is there in the directory but still I am getting error
Please help me in resolving this.

**Comment by fengyuxi55** [comment]
I met this issue before, I think it's as to you have 2 more python env in your system. 
I fix it by deleting the $FRCN and re-git it.

**Comment by chaitu2289** [comment]
Thanks for responding.  I have compiled caffe with python2.7 and ran demo.py with different version of python. I solved by re-compiling the code.
