### ISSUE TITLE
Expecting mat file of proposals while resuming training from snapshot

### ISSUE THREAD

**Issue by ajeetksingh** [rbgirshick/py-faster-rcnn#153]
Hi,

I tried to resume the training from 27000 iterations on the coco dataset, with the help from the resources available here. Thanks @eternautaCAT.

When I resume the training, faster rcnn expects the proposals mat file, which is not stored anywhere on the machine. And I do not think faster rcnn requires it. Did you guys face this kind of problem before?

Thanks.

You can find the relevant log below:

`coco_2014_train gt roidb loaded from /home/exx/ajeet/py-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
Loading selective_search boxes
1 / 82783
Traceback (most recent call last):
  File "./tools/train_net.py", line 107, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 72, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 69, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 121, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/datasets/coco.py", line 124, in selective_search_roidb
    return self._roidb_from_proposals('selective_search')
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/datasets/coco.py", line 150, in _roidb_from_proposals
    method_roidb = self._load_proposals(method, gt_roidb)
  File "/home/exx/ajeet/py-faster-rcnn/tools/../lib/datasets/coco.py", line 189, in _load_proposals
    raw_data = sio.loadmat(box_file)['boxes']
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 57, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: '/home/exx/ajeet/py-faster-rcnn/data/coco_proposals/selective_search/mat/COCO_train2014/COCO_train2014_0000002/COCO_train2014_000000262145.mat'`

**Comment by eternautaCAT** [comment]
Are you using the ene2end method? Make sure you are. And take care that you faster_rcnn_end2end.yml file has the following line in train and test:   HAS_RPN: True 

Also, remember pass that file when you run the training with the --cfg flag.

In my case, I start to run my training in this way:
$ ./tools/train_net.py --gpu 0 --solver models/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb cars_train --cfg experiments/cfgs/faster_rcnn_end2end.yml

**Comment by ajeetksingh** [comment]
Thanks for the reply, @eternautaCAT.
I have made sure that all the things which you asked me to take care of is already taken.
I start my training the same way, you mentioned.

My issue starts, when I try to resume the training from a snapshot. I changed the code accordingly, so that it would take the solverstate instead of the pretrained weights by omitting the --weights flag from the command and adding the --snapshot flag to it. I have also made the changes at relevant places in  the code to reflect the same. But somehow, it's not working. As you can see the log in thread, it gets stuck in the _load_proposals method. Did you face this problem while resuming from snapshot?

Thanks.

**Comment by eternautaCAT** [comment]
No, i have not this problem. But seems like you are using external region proposal (I had this problem by the way), and you should not do that. This is the hole point of this paper. Take a look in what parts the net are trying to use external region proposal instead the RP network (you can find some if statements) and maybe you can see what condition you are not handling well.

**Comment by ajeetksingh** [comment]
As @eternautaCAT mentioned, I was using 'selective_search' switch for RPN instead of 'gt'  in lib/fast-rcnn/config.py/

Now training runs smoothly. Thanks @eternautaCAT ..
