### ISSUE TITLE
Bounding box extraction

### ISSUE THREAD

**Issue by Ethiral** [rbgirshick/py-faster-rcnn#182]
How to crop the detected objects for multiple image inputs?

**Comment by regpuro** [comment]
Try adding this code in demo.py to crop detected objects - 

import cv2
img = cv2.imread("test.png") 'name of the file to be cropped
crop_img = img[535:745, 634:1066] #bounding box  coordinates detected
cv2.imwrite("test3_cropped.png", crop_img)

// Y1,, Y2, X1, X2 should be available in demo.py  - 
            plt.Rectangle((bbox[0], bbox[1]),
                          bbox[2] - bbox[0],
                          bbox[3] - bbox[1], fill=False,
                          edgecolor='red', linewidth=3.5)

Hope this helps.

**Comment by Ethiral** [comment]
Yes,that does the trick.
