### ISSUE TITLE
Understanding the RPN

### ISSUE THREAD

**Issue by PeterQFR** [rbgirshick/py-faster-rcnn#184]
Hi I'd like to get a better understanding of the blob shapes in the RPN section of the endtoend training NN.

My understanding is that the output from the main convolution is shared between two convolution layers:

1. rpn_cls_score, and
2. rpn_bbox_predict.

The output from these layers should be an 18 channel (openCV terminology) image for 1. and a 36 channel image for 2. Is this correct?

If it is, then outputs from 2. is 36, which the [model ](https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/VGG16/faster_rcnn_end2end/train.prototxt)(endtoend) says is 4 x 9 anchors. I understand the 9 anchors are combinations of 3 scales and 3 aspect ratios, what then is the 4? Is that the limit of the number objects of each class that can be found? Or is it something like (centrex, centrey, width and height)? I'm not understanding how this blob is structured and how it is then trained with a smoothL1Loss. What is the structure of the ground truth for training?

Any help in correcting/confirming my understanding would be appreciated.

**Comment by happyharrycn** [comment]
rpn_bbox_predict is the predicted deltas of original bounding boxes (i.e. anchors). The size of rpn_bbox_predict is 36*height*width, where 36 = 4*9. 4 is the dimension of bounding box coordinates (check the re-parameterization of the paper). And 9 is the number of anchors.

**Comment by ericromanenghi** [comment]
Please, close the issue if you could solve your issue.

**Comment by PeterQFR** [comment]
The Paper had additional information that I had overlooked
