### ISSUE TITLE
How to load ROIs?

### ISSUE THREAD

**Issue by JohnnyY8** [rbgirshick/py-faster-rcnn#187]
Hi, everyone. I have some questions about loading RoIs by my own python layer?
I have seen tow files, "models/pascal_voc/ZF/faster_rcnn_alt_opt/faster_rcnn_test.pt" and "models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt" as following:
![image](https://cloud.githubusercontent.com/assets/12611573/15278540/b2a6ff20-1b4c-11e6-8836-7d2378936120.png)
![image](https://cloud.githubusercontent.com/assets/12611573/15278550/d8eca77a-1b4c-11e6-94dd-a0df623a193d.png)
I am confused about how to load RoIs generated by myself, like RoIDataLayer?
I noticed that im_detect function have a argumet named "boxes". Is that RoIs?
Can anyone help? The problem is pressing.
Thanks a lot!

**Comment by ajeetksingh** [comment]
How are you generating RoIs? Are you using any region proposal methods?

The "boxes" argument in the im_detect is the detections obtained by the learned network on a give image. That is not the RoI which you are talking about.

You should look into following function to know more about it. 
https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/roi_data_layer/roidb.py

Hope it helps.

**Comment by JohnnyY8** [comment]
Thanks first, @ajeetksingh 
Yes, I use other region proposal methods. But I do not know how to make my RoIs into network, as a blob? By the way, may I ask that is the RoI equial to the proposal?

**Comment by ajeetksingh** [comment]
From my limited understanding I can say that the RoIs are the proposals.

If you are using any other region proposals methods, you may have store those proposals somewhere on your disk. If that's the case, you should make the changes in the YML files present in 'experiments' folder. For example, if you are using end2end architecture:

`EXP_DIR: faster_rcnn_end2end
TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt <change it to selective search if you are using it>
  BG_THRESH_LO: 0.0
TEST:
  HAS_RPN: True`

If it doesn't work, try to incorporate this change into `config.py` in `lib/fast-rcnn`
You can also check the lib/datasets/coco.py where they load the proposals from the mat files.
I am assuming that you are doing experiments on COCO dataset.
Hope it helps.

**Comment by JohnnyY8** [comment]
I also think the RoIs are the proposals.
As you said, I stored my own proposals on disk and wanted to load them into network. So the RPN will not be used, and I set cfg.TEST.HAS_RPN to False. But I got a lot of bugs, because I do not know how to deal with the blob['rois']. As for cfg.TEST.HAS_RPN, I think that it decides whether data flow throughs the RPN?
And I never try to see the YML files, because I am not quite sure the function of parameters.
These problem is a little pressing for me, so if you don't mind, "johnny9141hotmail.com" is my email address.
Anyway, thank you for your help!

**Comment by JohnnyY8** [comment]
You said "the "boxes" argument in the im_detect is the detections obtained by the learned network on a give image". I still do not understand what is it clearly?
I didn't use the coco dataset and the YML files seems doesn't work. It doesn't config where load my own proposals.
I will check the coco.py file. In lib/fast_rcnn/test.py, if I set cfg.TEST.HAS_RPN to False, there are a lot of errors that I do not  understand. @ajeetksingh

**Comment by ericromanenghi** [comment]
If you want to use your own region proposals, you should use https://github.com/rbgirshick/fast-rcnn

The hole point of py-faster-rcnn is don't use external regions proposal.

**Comment by JohnnyY8** [comment]
Thank you! @ericromanenghi 
I did not understand the differences between fast rcnn and faster rcnn, but it is better.
If I do not want to use RPN, the fast rcnn is enough for me, right?

**Comment by ajeetksingh** [comment]
@ericromanenghi is right... you should use the fast rcnn if you are using your own proposals. @JohnnyY8.
Somehow, I missed telling you that... What was I thinking?

**Comment by JohnnyY8** [comment]
@ajeetksingh ha, thank you again!
You guys help me a lot!
