### ISSUE TITLE
testing py_faster_rcnn for "alt_opt" 

### ISSUE THREAD

**Issue by anas-899** [rbgirshick/py-faster-rcnn#188]
I successfully trained Inria Dataset by using "train_faster_rcnn_alt_opt.py" and by help of:
https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md

I tried to use "tools/test_net.py" for testing but it seems not working for "alt_opt" as I understood.

Is there another file like "test_faster_rcnn_alt_opt.py" for testing the "alt_opt" and I don't know about it?

**Comment by hgaiser** [comment]
Should work fine, it is also being used in:

https://github.com/rbgirshick/py-faster-rcnn/blob/master/experiments/scripts/faster_rcnn_alt_opt.sh

**Comment by anas-899** [comment]
@hgaiser , thanks for your replay.. I tried it and the same error message still exist:

File "./tools/test_net.py", line 88, in <module>
    imdb.set_proposal_method(cfg.TEST.PROPOSAL_METHOD)
  File "/home/user/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 55, in set_proposal_method
    method = eval('self.' + method + '_roidb')
  File "<string>", line 1, in <module>
AttributeError: 'inria' object has no attribute 'selective_search_roidb'

do you have any idea why it asks for selective_search method? or I missing something here

Thanks again

**Comment by hgaiser** [comment]
Seems like your inria dataset python file does not provide that function but I believe you already figured that out. Why it asks for selective search I don't know. You could check lib/fastrcnn/config.py, I remember it containing some options regarding the use selective search vs RPN.

**Comment by djr2015** [comment]
Does your file `experiments/cfgs/faster_rcnn_alt_opt.yml` (or more generally, the `.yml` file you're using to specify test configurations) contain :

```
TEST:
   HAS_RPN: True
```
?

I had this issue until I added it to my own `config.yml` file.

**Comment by anas-899** [comment]
yes, right ..
I discovered this later and fixed it
Thank you @hgaiser  @djr2015
