### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by desaipratik1991** [rbgirshick/py-faster-rcnn#189]
Hi 
 i am getting error while running make file. I have no idea about that..
![error](https://cloud.githubusercontent.com/assets/19326224/15285931/e44ef160-1b77-11e6-8c6f-0699169caded.png)

please help me to resolve this error 

Thank you.

**Comment by ericromanenghi** [comment]
Do you have installed cython, python-opencv, easydict (python packages)?

**Comment by desaipratik1991** [comment]
Hi

I have installed all these packages(cython, python-opencv, easydict). 
Thank you for your suggestion.

**Comment by ericromanenghi** [comment]
Could you solve your problem?

**Comment by desaipratik1991** [comment]
Hi

No i am still getting that error

*Thanks & Regards*
*Pratik Desai*



*M.E. (Embedded System)BITS Pilani K K Birla Goa
Campus Mobile: +91-7567204894*

*E-Mail: desai.pratik91@gmail.com <desai.pratik91@gmail.com> ,
   **h2014036@goa.bits-pilani.ac.in
<h2014036@goa.bits-pilani.ac.in>*

**Comment by ericromanenghi** [comment]
May you tell me how are you trying to compile? (Try to put the commands)

**Comment by desaipratik1991** [comment]
Hi
     Now i am trying with Linux environment still i am getting same error.
I have used this link-
https://github.com/rbgirshick/fast-rcnn  for run DEMO. I got error while
LIB MAKE.

Thank you

*Thanks & Regards*
*Pratik Desai*



*M.E. (Embedded System)BITS Pilani K K Birla Goa
Campus Mobile: +91-7567204894*

*E-Mail: desai.pratik91@gmail.com <desai.pratik91@gmail.com> ,
   **h2014036@goa.bits-pilani.ac.in
<h2014036@goa.bits-pilani.ac.in>*

**Comment by ericromanenghi** [comment]
fast-rcnn and py-faster-rcnn are too different repositories. Anyway, the codebase is shared and I think that both should compile. But if you are trying with fast-rcnn, I think that is a better idea to close this issue and open a similar issue in the other repo.

**Comment by desaipratik1991** [comment]
ok
