### ISSUE TITLE
How to use own proposals instead of RPN?

### ISSUE THREAD

**Issue by JohnnyY8** [rbgirshick/py-faster-rcnn#190]
Hi, everyone.
If I want use our own proposals generated by other methods instead of RPN. How should I change the code to ignore RPN and load my own proposals for "roi_pool_conv5" layer?
Can anyone help me?
Thanks a lot!

**Comment by happyharrycn** [comment]
You can train and test your detector using fast rcnn prototxt files instead of faster rcnn.

**Comment by JohnnyY8** [comment]
Woo, I realize my mistakes because of you.
Thank you @happyharrycn , it works.

**Comment by ericromanenghi** [comment]
Close the issue if you could solve your problem, please.
