### ISSUE TITLE
How to train faster_rcnn on objects with small size? If i need modify the size of anchors?

### ISSUE THREAD

**Issue by yytzjgsu** [rbgirshick/py-faster-rcnn#209]
I found that size of anchors may be not suitable for training a new model for detect small object.All images of my own dataset is 1920x1080,but the object is only 18x9.So it is necessary to adjust the size of anchors?
Any reply will be appreciated.

**Comment by dkislyuk** [comment]
see https://github.com/rbgirshick/py-faster-rcnn/issues/161

**Comment by yytzjgsu** [comment]
Thank u ,I haven‘t noticed this issue before.

在 2016-06-08 02:38:50，"Dmitry Kislyuk" <notifications@github.com> 写道：


see #161

**Comment by harjatinsingh** [comment]
Did only changing the image input size work for detecting smaller objects ? Or did you have to adjust anchor sizes as well. If you had to change the anchor sizes, how is that done ?
