### ISSUE TITLE
How to run py-faster-rcnn with X11 forwarding

### ISSUE THREAD

**Issue by aaronpolhamus** [rbgirshick/py-faster-rcnn#212]
I'm running py-faster-rcnn with cuDNN enabled on a g2.8xlarge EC-2 instance with Ubuntu 14.04 operating system. Everything's compiled and seems to be working fine. I log in to the remote instance via: 

`ssh -X -i "<key.pem>" ubuntu@<IP address>`

I also enter the command: `export DISPLAY=:0`

Running `./tools/demo.py` the output looks good: 

    Loaded network /home/ubuntu/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Demo for data/demo/000456.jpg
    Detection took 0.543s for 300 object proposals 
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Demo for data/demo/000542.jpg
    Detection took 0.506s for 161 object proposals
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Demo for data/demo/001150.jpg
    Detection took 0.507s for 194 object proposals
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Demo for data/demo/001763.jpg
    Detection took 0.507s for 196 object proposals
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Demo for data/demo/004545.jpg
   Detection took 0.541s for 300 object proposals

But graphical output is not rendered in my XQuartz window. 

Has anyone else solved this? Need to figure out how to use AWS hardware but with local visualization capabilities. Checked here, but I wasn't able to solve my problem: https://github.com/BVLC/caffe/issues/861

**Comment by ricepot100** [comment]
If you install xshell with xmanager, you could config the xshell: 
File-->Connection--->SSH--->Tunneling--->X11 Forwarding,  check select the "Forward X11 connections to: "--->Xmanager

**Comment by aaronpolhamus** [comment]
so the problem was actually related to matplotlib. see StackExchange for the process that I went through to get this all running: http://stackoverflow.com/questions/37663127/how-to-run-py-faster-rcnn-with-x11-forwarding
