### ISSUE TITLE
Compressing faster-rcnn models?

### ISSUE THREAD

**Issue by n3011** [rbgirshick/py-faster-rcnn#22]
Hi @rbgirshick , is there any way to compress the trained models using faster-rcnn?

**Comment by peternara** [comment]
i need this process for more fast.~

**Comment by JoeLoveFannie** [comment]
In fact, it's provided in /tools/compress.py. You can just write a new protext for the compressed net. Then run the .py file. Good Luck

**Comment by marifnst** [comment]
hi all & @rbgirshick 

Is compressed tool has the same purpose with deep compress (https://arxiv.org/abs/1510.00149) ?

thanks

**Comment by marifnst** [comment]
hi @rbgirshick

thank you for **compress** code, so i can create my own compress tool [my code](https://github.com/marifnst/SampleCaffeModelCompression)

thanks

**Comment by tangshi** [comment]
`tools/compress_net.py`script helps me to compress the caffemodel file from 546.8MB to 196.5MB, however, the GPU memory cost is still very high (it cost 5072MB at present and 5406MB before compressed).

Is there any solution to reduce the GPU memory cost?
