### ISSUE TITLE
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'

### ISSUE THREAD

**Issue by GeorgiAngelov** [rbgirshick/py-faster-rcnn#221]
I finally got everything to compile and I tried to run the demo. I got the following error and the gplot windows are empty and no images are shown:

Loaded network /home/ubuntu/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/000456.jpg
Detection took 0.538s for 300 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/000542.jpg
Detection took 0.501s for 161 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/001150.jpg
Detection took 0.504s for 194 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/001763.jpg
Detection took 0.502s for 196 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/004545.jpg
Detection took 0.535s for 300 object proposals
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'

**Comment by GeorgiAngelov** [comment]
I fixed this by doing "sudo apt-get install python-gobject-cairo"

**Comment by newwhitecheng** [comment]
sudo apt-get install python-gi-cairo

**Comment by johackim** [comment]
```bash
# On ArchLinux
sudo pacman -S python-cairo
```

**Comment by abdRumman** [comment]
> I fixed this by doing "sudo apt-get install python-gobject-cairo"

didn't worked with me :(

**Comment by abdRumman** [comment]
> sudo apt-get install python-gi-cairo

works with me thanks!

**Comment by HussamSoufi** [comment]
In case anyone is using python3 with pi, then just change the command to "sudo apt-get install python3-gi-cairo"

**Comment by luisliborio** [comment]
Holy c... halleluiah!! Thank you SO much! Worked for me:

sudo apt-get install python-gi-cairo

**Comment by ZOrfeas** [comment]
> In case anyone is using python3 with pi, then just change the command to "sudo apt-get install python3-gi-cairo"

A thanks is due :). 
Thanks, that 3 has cost me too many hours in too many different occasions

**Comment by FaridaAlakbarli** [comment]
> In case anyone is using python3 with pi, then just change the command to "sudo apt-get install python3-gi-cairo"

Thanks so much, it worked!
