### ISSUE TITLE
Difference between the demo model and pre-trained ImageNet model

### ISSUE THREAD

**Issue by GBJim** [rbgirshick/py-faster-rcnn#222]
Hi
I am confused with these two models:

(A).The VGG16 demo network trained for object detection on PASCAL VOC 2007
(B).The pre-trained ImageNet model that downloaded from the fetch_imagenet_models.sh

My understanding is that if I fine-tuned the model(B) on Pascal VOC 2007 data, I will get model(A)
Is that correct?

**Comment by karaspd** [comment]
@GBJim Yes, If you fine-tuned the model B same way the author did you probably will get model A. 
You can fine-tune it in any way like changing layers, solvers and hyper parameters. With any fine tuning you can get several models like A that you can test on it.

**Comment by GBJim** [comment]
@karaspd : Thank you! :)
