### ISSUE TITLE
(Easy deploy) Easy ways to predict an image with the trained network?

### ISSUE THREAD

**Issue by tohnperfect** [rbgirshick/py-faster-rcnn#230]
I have successfully trained the network on my own dataset by following this [tutorial](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md). Now I am wondering what is the easiest way for me to make prediction on an unlabelled image. Please note that I am a very beginner CAFFE and Deep NN user.

**Comment by deboc** [comment]
Hi,
You can start to have a look on the [demo](https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/demo.py) script from the original repo, and finetune it to fit your needs.

**Comment by tohnperfect** [comment]
Hi @deboc,

Thank you very much. Now I manage to get prediction results.
