### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by hengck23** [rbgirshick/py-faster-rcnn#249]
Anyone has this problem?
Did not compile _caffe.cpp correct?
The layer phase variable cannot be set?

I0712 17:21:04.101418 87972 net.cpp:425] proposal <- rpn_cls_prob_reshape
I0712 17:21:04.102417 87972 net.cpp:425] proposal <- rpn_bbox_pred
I0712 17:21:04.102417 87972 net.cpp:425] proposal <- im_info
I0712 17:21:04.102417 87972 net.cpp:399] proposal -> rois
Traceback (most recent call last):
  File "....\python\demo_1\py\main.py", line 88, in <module>
    net = caffe.Net(prototxt, caffemodel, caffe.TEST)
AttributeError: can't set attribute

**Comment by lxd7714059** [comment]
Hi @hengck23 
have you solved that? i met the same issue with you.

**Comment by hengck23** [comment]
This issue is due to using different version of caffe, python files.
I solved this issue.

I use windows version of caffe.  In this version, the phase attribute is already exposed. Hence I modified  Ross's version as follows:

python_layer.hpp:

PythonLayer(PyObject* self, const LayerParameter& param)
      : Layer<Dtype>(param), self_(bp::handle<>(bp::borrowed(self))) { }

  virtual void LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
	  
    // Disallow PythonLayer in MultiGPU training stage, due to GIL issues
    // Details: https://github.com/BVLC/caffe/issues/2936
    if (this->phase_ == TRAIN && Caffe::solver_count() > 1
        && !ShareInParallel()) {
      LOG(FATAL) << "PythonLayer is not implemented in Multi-GPU training";
    } 
    self_.attr("param_str") = bp::str(
        this->layer_param_.python_param().param_str()); 
    **//self_.attr("phase") = static_cast<int>(this->phase_);** 
    self_.attr("setup")(bottom, top);
  }

**Comment by lxd7714059** [comment]
@hengck23 
Thanks a lot

**Comment by mdadhich** [comment]
@hengck23 @ShadowLau @rbgirshick 
I am trying to run the demo.py from faster rcnn ( link - https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/demo.py) and its giving me this error - 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-93f0c844edaf> in <module>()
     22         caffe.GPU_ID = args.gpu_id
     23     print(cfg.GPU_ID)
---> 24     net = caffe.Net(prototxt, caffemodel, caffe.TEST)
     25 
     26     print '\n\nLoaded network {:s}'.format(caffemodel)

AttributeError: can't set attribute

I have already tried above mentioned changes( that is, commenting //self_.attr("phase") = static_cast(this->phase_); in python_layer.hpp file), still its giving me same error, any thoughts why its happening ? 
Thanks in advance.
