### ISSUE TITLE
Running training without flipping returns reshape errors.

### ISSUE THREAD

**Issue by duygusar** [rbgirshick/py-faster-rcnn#254]
I am having an out of memory problem (details here: https://github.com/rbgirshick/py-faster-rcnn/issues/253) In an attempt to decrease memory usage I have been experimenting, and although I don't think flipped images are hold in the memory or anything (since I have my batchsizes as 1) I am trying whatever might help. Anyway, I have set

  # Use horizontally-flipped images during training?
__C.TRAIN.USE_FLIPPED = False

and now I have a great deal of reshape errors. Why is this?

File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/duygu/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/duygu/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 53, in __init__
    self.solver.net.layers[0].set_roidb(roidb)
  File "/home/duygu/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 68, in set_roidb
    self._shuffle_roidb_inds()
  File "/home/duygu/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 35, in _shuffle_roidb_inds
    inds = np.reshape(inds, (-1, 2))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged

**Comment by manipopopo** [comment]
```python
np.reshape(inds, (-1, 2))
```
The number of valid `roidb` must be even.  
Make the number of records in the `train.txt` be even (assuming records in `train.txt` are all [_valid_](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/fast_rcnn/train.py#L130)).

Besides, setting `__C.TRAIN.USE_FLIPPED` to `False` won't change the peak GPU memory usage.

**Comment by duygusar** [comment]
@manipopopo  

Thank you, though I do have an even number of training images in train.txt It should be all valid, I am just running on voc 2007.

yes, I was not really expecting it to be related to the GPU, I tried setting the batches to 1 only and decreasing no of proposals with no luck so I was just experimenting around. When you crop images, you forward ten images at once (kind of like a 10 image batch) and need that much memory so I thought -maybe- it is the same for flipped images though it might be like mirroring, just doubling the number of images in the dataset. 

I still don't know why it consumes so much memory. I have run the alternative optimization and didn't have a problem. Well true it alternates instead of joint learning but still I think the memory consumption is relatively way too much.

**Comment by manipopopo** [comment]
- If you run `experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc`, it will load the training data specified in `data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt`, which contains 5011 records.
`np.reshape(inds, (-1, 2))` can't reshape inds of odd length (5011).

- Even the number of images (or `roidb`) grows, `roi_data_layer` still takes `cfg.TRAIN.IMS_PER_BATCH` (which is **1** in end-to-end training strategy) images per iteration.

- Running `experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc` takes about 2 GB GPU memory on my desktop computer (CUDA 8, CuDNN 4).

**Comment by duygusar** [comment]
@manipopopo  Thank you, you are right! I think I wasn't paying enough attention.

Yea, the problem is I have a Tesla C2070, which has quite good memory but is architecture 2.0 and I can't use cuDNN with 2.0. cuDNN seems to make a great deal of difference. Thanks for writing that, I have borrowed a GPU from lab which is not top notch but is architecture 3.0 so I can try cuDNN. I am relieved to hear it only requires 2GB memory.
