### ISSUE TITLE
low evaluation results (mAP) on VOC 2007 using python eval on ZF net???

### ISSUE THREAD

**Issue by hengck23** [rbgirshick/py-faster-rcnn#256]
Hi, I am getting low results of Mean AP = 0.444 using the python eval code provided. Please let me know if my results are correct?

setting:
ZF_faster_rcnn_final.caffemodel  (in dowloaded "faster_rcnn_models.tgz") 
test.prototxt
faster_rcnn_end2end.yml
TEST IMDB="voc_2007_test"

my results:
~~~~~~~~
Results:
0.493
0.508
0.386
0.284
0.130
0.565
0.504
0.650
0.215
0.347
0.604
0.584
0.674
0.540
0.420
0.177
0.305
0.511
0.660
0.316
0.444 (mAP)
~~~~~~~~

Results computed with the unofficial Python eval code.
Results should be very close to the official MATLAB eval code.
Recompute with `./tools/reval.py --matlab ...` for your paper.

Press any key to continue

**Comment by hengck23** [comment]
If I fine tune the from the pretrained imagenet, I got mAP = 60.4 for ZF_Net.
So I think there is no issue.

**Comment by thomaspreece** [comment]
The downloaded model does not have lower performance. You were running the evaluation with the incorrect prototxt file. The downloaded models are trained using the faster_rcnn_alt_opt method, so you should of used the faster_rcnn_alt_opt/faster_rcnn_test.pt.
For all intents and purposes the two model files are the same except for some reason a couple of layers are renamed on the end2end version and hence when you run it in caffe it doesn't use the pretrained weights for that layer as it cannot match them to the name, this results in random weights being assigned to that layer and is the reason why running the evaluation multiple times results in slightly different accuracies.
