### ISSUE TITLE
Error on training on two classes from custom dataset

### ISSUE THREAD

**Issue by cyberdecker** [rbgirshick/py-faster-rcnn#257]
I'm trying to train two classes, in which one is already cropped and another is background. The annotations of the cropped is as the following:

`#numclass 0 0 width height`

I have followed the instructions [here](http://sgsai.blogspot.com.br/2016/02/training-faster-r-cnn-on-custom-dataset.html) and [here](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md), but it is not working. I get the following error:

```
Appending horizontally-flipped training examples...
train gt roidb loaded from /home/giseli/py-faster-rcnn/data/cache/train_gt_roidb.pkl
done
Preparing training data...
done
1362 roidb entries
Output will be saved to `/home/giseli/py-faster-rcnn/output/faster_rcnn_end2end/train`
Filtered 1362 roidb entries: 1362 -> 0
Computing bounding-box regression targets...
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/giseli/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/giseli/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 40, in __init__
    rdl_roidb.add_bbox_regression_targets(roidb)
  File "/home/giseli/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 48, in add_bbox_regression_targets
    assert len(roidb) > 0
AssertionError
```

Any clues?

**Comment by GBJim** [comment]
Hi @cyberdecker 
Maybe you can try to delete the cache files in data/cache/ folder and try again

**Comment by eldor4do** [comment]
You can check your load_annotations code also once again, whether it is being able to load the annotations correctly or not.

**Comment by cyberdecker** [comment]
Deleted the cache files, resolved the error, but I got another error... Maybe is the load_annotations. What is the expected output of the load_annotations and how I could debug it?

The error:

```
Loading pretrained model weights from data/imagenet_models/ZF.v2.caffemodel
I0715 09:19:48.883231  4895 upgrade_proto.cpp:66] Attempting to upgrade input file specified using deprecated input fields: data/imagenet_models/ZF.v2.caffemodel
I0715 09:19:48.883261  4895 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.
W0715 09:19:48.883265  4895 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
I0715 09:19:48.886101  4895 net.cpp:761] Ignoring source layer pool5_spm6
I0715 09:19:48.886122  4895 net.cpp:761] Ignoring source layer pool5_spm6_flatten
I0715 09:19:48.914810  4895 net.cpp:761] Ignoring source layer drop6
I0715 09:19:48.927350  4895 net.cpp:761] Ignoring source layer relu7
I0715 09:19:48.927382  4895 net.cpp:761] Ignoring source layer drop7
I0715 09:19:48.927384  4895 net.cpp:761] Ignoring source layer fc8
I0715 09:19:48.927386  4895 net.cpp:761] Ignoring source layer prob
Solving...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 129, in train_rpn
    max_iters=max_iters)
  File "/home/giseli/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/giseli/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/giseli/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 144, in forward
    blobs = self._get_next_minibatch()
  File "/home/giseli/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 63, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/giseli/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 22, in get_minibatch
    assert(cfg.TRAIN.BATCH_SIZE % num_images == 0), \
ZeroDivisionError: integer division or modulo by zero


```

**Comment by cyberdecker** [comment]
Okay, so I'm trying to debug my file [here](https://gist.github.com/cyberdecker/ac39eb3dfea9bc21ee955e92edcee782), adapted from [this](https://github.com/deboc/py-faster-rcnn/blob/master/lib/datasets/inria.py), by calling directly the class. But what are the functions that matter to debug? When I call directly the class, it only load the path for the images, I don't understand how it calls the another methods in the class.

**Comment by Pessanha24** [comment]
Hi @cyberdecker ,

I obtain the same error, did you solve it?

Thanks

**Comment by sbrugman** [comment]
The same error occurs to me too. Anyone has got a solution?

**Comment by cyberdecker** [comment]
The problem was in the function that loads the annotations file, you need to debug it. To debug, you can create a small piece of code at libs/datasets and in the code call the functions related to your dataset. So, for example if using INRIA database, you import inria from datasets and call the function load_annotations (or something). You need to output the roi of each annotation to check if is consistent.

**Comment by LK1711** [comment]
@cyberdecker could you please share this piece of code you mentioned? I have been facing the same problem.

**Comment by liceHuang** [comment]
I have this problem caused the content of
py-faster-rcnn-master\data\VOCdevkit2007\VOC2007\ImageSets\Main\trainval.txt
in this txt file we shoul give only image name without the image class label,
e.g :if we have an image named test01.jpg in 
py-faster-rcnn-master\data\VOCdevkit2007\VOC2007\JPEGImages
we shoul fill test01 in trainval.txt
in orignal voc_2007_data trainval.txt is filled as test01 1 or test01 -1, we should modify it.
