### ISSUE TITLE
Training problem : Value Error

### ISSUE THREAD

**Issue by n3011** [rbgirshick/py-faster-rcnn#26]
I am trying to train a model in dataset with 61 classes including background and hence i set the num of output in prototxt file to 61 and that of bbox reggression to 244. 
But I am getting this error during stage1 fast rcnn training. Unable to figure it out. 

 `self.bbox_stds[:, np.newaxis]`
ValueError: operands could not be broadcast together with shapes (244,4096) (240,1)

**Comment by gavinmh** [comment]
Hi @n3011 . I am encountering the same error; my data set has two classes. How did you resolve this?

**Comment by ednarb29** [comment]
I have a similar problem to this one. Does someone has a solution?

**Comment by n3011** [comment]
@gavinmh @ednarb29 check ur prototxt files. make sure all fields are correct

**Comment by EloiZ** [comment]
Make sure you change the prototxt files (train and test) as explained in https://github.com/deboc/py-faster-rcnn/tree/master/help and https://github.com/andrewliao11/py-faster-rcnn
Also do not forget to change the first line of solver.prototxt to take into account the train.prototxt
`train_net: "models/<YOURDATASET>/VGG16/faster_rcnn_end2end/train.prototxt"`

**Comment by ednarb29** [comment]
Yes, I forgot to adapt the path in the solver. ;)

Thanks!
