### ISSUE TITLE
Training with Mini-Batch size greater than 1

### ISSUE THREAD

**Issue by ice-pice** [rbgirshick/py-faster-rcnn#267]
Hi,

I am trying to train py-faster-rcnn using a mini-batch size of 4.
However, when I look at all the python layers in RPN, I found that it supports a mini-batch of only 1.
For example <a href="https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/rpn/proposal_layer.py#L61">here</a>, there is an assert which doesn't allow a greater than 1 mini-batch.

I am currently trying to modify the python code to support a bigger mini-batch but the task seems daunting and I am not even sure if it can be done with slight modifications or do I have to make huge changes.

Would really appreciate if someone with a better insight can give some opinions/suggestions/directions.
Thanks!

**Comment by GBJim** [comment]
@ice-pice 
This closed issue might give you some clues:
[#51](https://github.com/rbgirshick/py-faster-rcnn/issues/51)

**Comment by ice-pice** [comment]
Thanks but this is a workaround.
I have modified the data layer and rpn layers to accept greater mini-batch.
Training the model currently....

**Comment by GBJim** [comment]
@ice-pice That's great!
Would you like to share those modifications later?

**Comment by ice-pice** [comment]
@GBJim Let me validate the changes first.
I might have done a lousy job from software engineering perspective but if it works, I won't mind sharing!

**Comment by zimenglan-sysu-512** [comment]
@ice-pice can you share your modification? thanks a lot.

**Comment by babylonico** [comment]
@ice-pice did you validate your work around?

**Comment by ice-pice** [comment]
@zimenglan-sysu-512 @babylonico Please find appropriate changes https://github.com/ice-pice/py-faster-rcnn . It gives me equivalent performance compared to using same iter_size. @GBJim

**Comment by juancamilog** [comment]
@ice-pice can you please make a pull request?

**Comment by Fuckmi** [comment]
@ice-pice  How can you get batchsize more than one? Because the input image sizes differ, so they cannot be input  as a batch, so the input batchsize should be one.

**Comment by ice-pice** [comment]
Can you see my repo where I make the changes. 
https://github.com/ice-pice/py-faster-rcnn

**Comment by ujsyehao** [comment]
Hi, I have a problem, 'Faster RCNN' says Ncls =256 , 256 is the mini-batch size , but comments say batch size is 1, so I confused, 256 is the anchors of a image?

**Comment by liangzimei** [comment]
@ujsyehao 1 is the number of image each iteration, 256 is the number of rois(pos and neg) in this image, So 256 is the true batchsize often grasped.

**Comment by ujsyehao** [comment]
Thank you! @liangzimei

**Comment by sujinpeng** [comment]
what's the meaning of the im_inds?

**Comment by crazysal** [comment]
please clarify ... @ice-pice 
so each image contributes 256 roi's ? 
and if I have  4 images in mini-batch, after roi-align tensor shape will become `4*256 X C X H X W` ?
