### ISSUE TITLE
Many bounding boxes when running demo.py

### ISSUE THREAD

**Issue by cemsaz** [rbgirshick/py-faster-rcnn#276]
When I run ./tools/demo.py --cpu --net zf , I see many bounding boxes. How can I fix this?
![screen shot 2016-07-27 at 9 23 25 am](https://cloud.githubusercontent.com/assets/11336887/17176726/043236f8-53dc-11e6-8a60-e64914722ee7.png)

**Comment by marifnst** [comment]
you can follow solution from this thread https://github.com/rbgirshick/py-faster-rcnn/issues/123

hope this help.

**Comment by cemsaz** [comment]
@marifnst That totally worked ! Thanks.

**Comment by plopd** [comment]
@marifnst Unless I overlooked something, there is nothing mentioned in [#123](https://github.com/rbgirshick/py-faster-rcnn/issues/123) that (directly) solves the issue opened here.

@cemsaz How exactly did you solve the issue and got fewer bounding boxes?

**Comment by Pratosha-29** [comment]
@plopd In the code demo.py , change the values of NMS_THRESH to 0.1 or lesser. Higher the value of threshold more is the bounding boxes created.
