### ISSUE TITLE
error in compiling gpu_nms.cpp : cannot convert  from '__pyx_t_5numpy_int32_t *' to 'int *'	 

### ISSUE THREAD

**Issue by hengck23** [rbgirshick/py-faster-rcnn#28]
Dear all,

I have this error when trying to compile gpu_nms.cpp
(using python setup.py build_ext --inplace)

 In function 'PyObject* __pyx_pf_3nms_7gpu_nms_gpu_nms(PyObject*, PyArrayObject*, PyObject*, __pyx_t_5numpy_int32_t)':
error: invalid conversion from '__pyx_t_5numpy_int32_t* {aka long int*}' to 'int*' [-fpermissive]

In file included from nms\gpu_nms.cpp:253:0:
nms\gpu_nms.hpp:1:6: error:   initializing argument 1 of 'void _nms(int*, int*, const float*, int, int, float, int)' [-fpermissive]
nms\gpu_nms.cpp: In function 'void __Pyx_RaiseArgtupleInvalid(const char*, int, Py_ssize_t, Py_ssize_t, Py_ssize_t)':

I am using windows 7 (64-bit)
My python is:
Python 2.7.10 |Anaconda 2.4.0 (64-bit)|

My numpy is:
Metadata-Version: 2.0
Name: numpy
Version: 1.9.3

Thank you very much.

**Comment by leejiajun** [comment]
me too

**Comment by leejiajun** [comment]
You could view my blog http://blog.csdn.net/jiajunlee/article/details/50373815. And see Q9.
Just need to change __pyx_t_5numpy_int32_t* to int*.

**Comment by tt-leader** [comment]
@leejiajun  Thank you for Q9, it works!
