### ISSUE TITLE
Makefile error: ( make: *** [all] Error 1 ) in building Cython modules in Windows

### ISSUE THREAD

**Issue by bybatkhuu** [rbgirshick/py-faster-rcnn#281]
I tried to build Cython modules in Windows
(According to installation instruction: https://github.com/rbgirshick/py-faster-rcnn#installation-sufficient-for-the-demo).
But when I tried to run "make" in cmd, these errors appeared: 

C:\caffe\caffe-windows\projects\Faster-RCNN\py-faster-rcnn\lib>make
python setup.py build_ext --inplace
running build_ext
skipping 'utils\bbox.c' Cython extension (up-to-date)
skipping 'nms\cpu_nms.c' Cython extension (up-to-date)
skipping 'nms\gpu_nms.cpp' Cython extension (up-to-date)
building 'nms.gpu_nms' extension
C:Program FilesNVIDIA GPU Computing ToolkitCUDAv7.5binnvcc.exe -Ic:\Anaconda2\lib\... (very long)
clude -Ic:\Anaconda2\PC -c nms/nms_kernel.cu -o build\temp.win-amd64-2.7\Release\...
error: command 'C:Program' failed: No such file or directory
make: *** [all] Error 1

It seems there are no separator, "\"(slash separation) and space between in these command to run, is it? I'm using Windows 8.1 x64 bit, NVIDIA GeForce GTX 460, CUDA Toolkit 7.5, Anaconda2-4.1.8(Python2.7), Windows Caffe, MinGW32 and other python libraries...
I have no idea, where should I fix this. Is there any idea to fix this?

**Comment by harora** [comment]
Sorry for a noob question but how to rebuild caffe in py-faster-rcnn/caffe-fast-rcnn/ >

It show all files up to date when i try to re build it.

**Comment by LiviuMarina** [comment]
Hi bybatkhuu, 

I am having the same issue. Did you managed to solve it?

Thanks!
