### ISSUE TITLE
KITTI Data Preparation for py-faster-rcnn

### ISSUE THREAD

**Issue by gy2256** [rbgirshick/py-faster-rcnn#296]
Hello,

I am trying to train the network with KITTI data set. (http://www.cvlibs.net/datasets/kitti/eval_object.php)

I notice the files I downloaded has the following structure:

_data_object_image_2
|-_training
   |-_image_2
     |- 000000.png
     |- 000001.png
     |- more .png files
|-_testing
   |-*image_2
     |- more .png files

_data_object_label
|-_training
   |- *label_2
      |- 000000.txt
      |- 000001.txt
      |- more .txt files

( \* means its a directory)

My question is how do I prepare these data before I feed them into the neural network? More specifically, Are there any tools I can use to convert them into IMDB format? I am really new to Caffe and any help would be greatly appreciated.

**Comment by neermat** [comment]
[This](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md) tutorial illustrates how to train py-faster-rcnn on another dataset with INRIA person as example datastet. This helped me in training the network on Caltech pedestrian dataset.

**Comment by karaspd** [comment]
@gyang1011, I am training with this dataset right now, but I have one issue on evaluating on different difficulty objects. Were you able to train and test with kitti? How do you compute false positive numbers in respect to object difficulty?
Any help would be greatly appreciated.
