### ISSUE TITLE
test demo shows no picture

### ISSUE THREAD

**Issue by xiaoyuliu** [rbgirshick/py-faster-rcnn#297]
The result is like:

Demo for data/demo/000456.jpg
Detection took 0.260s for 300 object proposals
Demo for data/demo/000542.jpg
Detection took 0.253s for 161 object proposals
Demo for data/demo/001150.jpg
Detection took 0.261s for 194 object proposals
Demo for data/demo/001763.jpg
Detection took 0.263s for 196 object proposals
Demo for data/demo/004545.jpg
Detection took 0.264s for 300 object proposals

At first it said "invalid DISPLAY", after adding
`import matplotlib`
`matplotlib.use('Agg')`
the error disappeared. Then there was no picture shown.

Is there any suggestion?

**Comment by twmht** [comment]
check this http://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/

you have to recompile python after installing tk-dev package.

for example, I use pyenv to manage the python executable and recompiling python is pretty easy.

```
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.11
```

after recompiling with python, you have to recompile the matplotlib from its source.

**Comment by codingsmallfish** [comment]
@twmht Thank you! This is indeed the problem of displaying and I have solved it through another similar way.
1. Set 
`backend : TkAgg`
 /PATH_TO_PYTHON/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
Now it works on my computer, but still no output when using ssh.
2. When ssh another computer, using 
`ssh -X server`
`echo $DISPLAY`
Then everything is OK.

**Comment by onkarganjewar** [comment]
FWIW, I had the same problem as @xiaoyuliu and I did the step 1 as mentioned by @xiaoyuliu 

> Set
backend : TkAgg
/PATH_TO_PYTHON/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
Now it works on my computer, but still no output when using ssh.

But, in my case the display was restored and I could see the picture **after** I commented out the 
`matplotlib.use('Agg')`

Hope this helps!
