### ISSUE TITLE
How to use faster rcnn to train on ImageNet detection dataset?

### ISSUE THREAD

**Issue by sunshineatnoon** [rbgirshick/py-faster-rcnn#3]
I want to train a model on ImageNet detection dataset, where should I start? Thx.

**Comment by PierreHao** [comment]
you should read code in lib/dataset/

**Comment by vladpaunescu** [comment]
Try this fork. I managed to train it on Imagenet 200. You have to provide the data in the format that faster-rcnn expects.

https://github.com/vladpaunescu/py-faster-rcnn

**Comment by wookayin** [comment]
@vladpaunescu Awesome, what a nice work! Could you please share your trained model as well?

**Comment by wangdelp** [comment]
@vladpaunescu Hi, thanks for posting you repo. Could you share the trained model weights? Thank you.
