### ISSUE TITLE
Error during training ZF with COCO dataset

### ISSUE THREAD

**Issue by chankim** [rbgirshick/py-faster-rcnn#305]
Hi, 
I'm trying to train ZF faster-rcnn using COCO dataset but met with an error. I think there is something I'm doing wrong and I hope someone here could help me find the problem. (By the way, I could train ZF with VOC 2007 with no problem). 
Please read to see if there's anything wrong with what I did below.
First, since the training searched for some proposal data under data/selectve_search or something, I changed proposal method from 'selective_search' to 'gt' (I don't know how there was no problem when training with VOC data).  in 'lib/fast_rcnn/config.py'.

```
__C.TRAIN.PROPOSAL_METHOD = 'gt' 
__C.TEST.PROPOSAL_METHOD = 'gt'
```

Second, the git repository had network and solver models for VGG16, VGG_CNN_M_1024 and ZF for pascal_voc, but it had only VGG16 and VGG_CNN_M_1024 for coco dataset. So I copied {solver.prototxt, train.prototxt and test.prototxt} from models/pascal_voc/ZF/faster_rcnn_end2end directory to models/coco/ZF/faster_rcnn_end2end directory. (Initially there was no models/coco/ZF directory).  I changed the first line of sovler.prototxt to 'train_net: "models/coco/ZF/faster_rcnn_end2end/train.prototxt"' and changed to 'stepsize: 350000' (I'll reduce it later). By the way, the train.prototxt file's python 'input-data' layer has set with 'param_str: "'num_classses': 21", but do I have to change it to 81? (I guess so and fix it next try).

The command I used is 
`experiments/scripts/faster_rcnn_end2end.sh 0 ZF coco --set EXP_DIR foobar RNG_SEED 42 TRAIN.SCALES "[400,500,600,700]"`

The training run ended like below.
```
....
I0823 15:20:10.533018 120518 solver.cpp:65] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/ZF.v2.caffemodel
Solving...
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/ckim/Neuro/py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 66, in forward
    rois_per_image, self._num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 191, in _sample_rois
    _get_bbox_regression_labels(bbox_target_data, num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 127, in _get_bbox_regression_labels
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
ValueError: could not broadcast input array from shape (4) into shape (0)
```
Before debugging for the error, I wish someone could tell me what I'm doing wrong.
Thanks in advance.

Just in case, I show the the directory structure under `data` directory here.(only training related directories shown).
```
├── cache -> faster_rcnn_shared/cache
├── coco
│   ├── annotations -> /home/ckim/Neuro/COCO/annotations/
│   └── images
│       ├── test2014 -> /home/ckim/Neuro/COCO/test2014
│       ├── test2015 -> /home/ckim/Neuro/COCO/test2015
│       ├── train2014 -> /home/ckim/Neuro/COCO/train2014
│       └── val2014 -> /home/ckim/Neuro/COCO/val2014
├── faster_rcnn_models
│   ├── VGG16_faster_rcnn_final.caffemodel
│   └── ZF_faster_rcnn_final.caffemodel
├── fast_rcnn_shared
│   ├── cache
│   │   ├── coco_2014_train_gt_roidb.pkl
│   │   └── voc_2007_trainval_gt_roidb.pkl
│   ├── imagenet_models
│   │   ├── VGG16.v2.caffemodel
│   │   ├── VGG_CNN_M_1024.v2.caffemodel
│   │   └── ZF.v2.caffemodel
│   └── selective_search_data
├── imagenet_models -> faster_rcnn_shared/imagenet_models
├── pylintrc
├── README.md
├── scripts
│   ├── fetch_faster_rcnn_models.sh
│   ├── fetch_imagenet_models.sh
│   └── fetch_selective_search_data.sh
├── selective_search_data -> fast_rcnn_shared/selective_search_data
├── VOCdevkit2007 -> ../../VOC2007/VOCdevkit
└── VOCdevkit2012 -> ../../VOC2012/VOCdevkit
```

**Comment by sidgan** [comment]
Are you able to run the `faster_rcnn_end2end.sh script` with the VGG16 or VGG_CNN_M_1024 models?

**Comment by chankim** [comment]
I tried running for VGG16 and COCO, and the final error is the same with what I get currently for ZF and COCO training case. See below. I found during Net::Init(net_param), rpn_loss_cls layer is being created twice and the error (bottom[0]->num() != bottom[1]->num()) is generated during the second creation. I don't know why the layer is created twice(layer factory called twice).
I0828 21:46:25.034386 32322 net.cpp:481] rpn_loss_cls <- rpn_labels
I0828 21:46:25.034405 32322 net.cpp:437] rpn_loss_cls -> rpn_cls_loss
I0828 21:46:25.034435 32322 layer_factory.hpp:76] Creating layer rpn_loss_cls
F0828 21:46:25.034744 32322 loss_layer.cpp:25] Check failed: bottom[0]->num() == bottom[1]->num() (2 vs. 1) The data and label should have the same number.
*** Check failure stack trace: ***
experiments/scripts/faster_rcnn_end2end.sh: line 57: 32322 Aborted                 (core dumped) ./tools/train_net.py --gpu ${GPU_ID} --solver models/${PT_DIR}/${NET}/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/${NET}.v2.caffemodel --imdb ${TRAIN_IMDB} --iters ${ITERS} --cfg experiments/cfgs/faster_rcnn_end2end.yml ${EXTRA_ARGS}

**Comment by chankim** [comment]
I found in the anchor_target_layer.py, at the final top[0] mapping, these lines : 

        labels = labels.reshape((1, height, width, A)).transpose(0, 3, 1, 2)
        labels = labels.reshape((1, 1, A * height, width))
        top[0].reshape(*labels.shape)
        top[0].data[...] = labels

This top[0] (= 1 or 0 label, meaning close to gt or not) becomes the bottom[1] of rpn_loss_cls layer. This rpn_loss_cls layer receives another input(=expected probability) bottom[0] from a convolution layer. Rpn_loss_cls layer (Softmax_With_Loss layer) 's bottom[0] input is of size (2, 2, A*height, width) and rpn_loss_cls layer expects bottom[0]->num() and bottom[1]->num() to be equal. I analzyed the anchor_target_layer.py code and understand (1,1,A*height,width) output format. About the expected probabiltiy output (2,2,A*height,width), what does the first 2, 2 mean? The second '2' can be  'for object' and 'for back-ground' but what about the first '2'?

**Comment by chankim** [comment]
It was because num is set to 2 from the data-input layer. So I set `cfg.TRAIN.IMS_PER_BATCH = 1` in tools/train_net.py before calling train_net.  But now I'm seeing this error :  
```
I0830 14:01:57.355264 17807 net.cpp:1023] Copying source layer drop7
I0830 14:01:57.355271 17807 net.cpp:1020] Ignoring source layer fc8
I0830 14:01:57.355276 17807 net.cpp:1020] Ignoring source layer prob
Solving...
I0830 14:01:57.466291 17807 net.cpp:602] ## : net_input_blobs_.size() : 0
Traceback (most recent call last):
  File "./tools/train_net_e2e.py", line 114, in <module>
    max_iters=args.max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/roi_data_layer/layer.py", line 145, in forward
    blobs = self._get_next_minibatch()
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/roi_data_layer/layer.py", line 63, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/roi_data_layer/minibatch.py", line 55, in get_minibatch
    num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/roi_data_layer/minibatch.py", line 125, in _sample_rois
    roidb['bbox_targets'][keep_inds, :], num_classes)
KeyError: 'bbox_targets'
```
Can any one give me any suggestion about what to do next?

**Comment by chankim** [comment]
I found the final(hopefully) problems! in the train.prototxt file, I changed some numbers like below.
param_str num_classes => 81 (from 21) for input-data layer and roi-data layer
inner_product_param num_output => 81 (from 21) for cls_score layer
inner_product_param num_output => 324 (from 84) for bbox_pred layer
Now the training is running for more than 30 minutes!

**Comment by FaridehForoozandeh** [comment]
I have the same problem chankim. But I could not solve it by changing train.prototxt. every thing looks fine but I do know I still have these errors. Please help me regarding that. Thanks
