### ISSUE TITLE
A demo question about gpu

### ISSUE THREAD

**Issue by wangha43** [rbgirshick/py-faster-rcnn#315]
I am running a demo by GPU under debian 8,but it does not display the images which shows while running it with '--cpu'.
To find the reason,I added a line in demo.py:
`def vis_detections(im, class_name, dets, thresh=0.5):`
`    """Draw detected bounding boxes."""`
`   inds = np.where(dets[:, -1] >= thresh)[0]`
`    print len(inds) //added`
`   if len(inds) == 0:`
`       return`

it print all 0 by gpu.I am doubting whether this problem is caused by my gpu.
I am using GTX 1060 and cuda toolkit 8.0,the cudnn version is 4.0.
When `make runtest`.I also found some test failed.

`[  FAILED  ] 5 tests, listed below:`
`[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionCuDNN, where TypeParam = float`
`[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientCuDNN, where TypeParam = float`
`[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float`
`[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSobelConvolutionCuDNN, where TypeParam = float`
`[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionGroupCuDNN, where TypeParam = float
`

**Comment by Jaspereclipse** [comment]
I am wondering if it is because you are using CUDNNv4. I would suggest using cudnnv5 (fix compatibility issue following #237). Works for me using GTX 1070.

**Comment by wangha43** [comment]
@Jaspereclipse It only work under cudnn v4

**Comment by Timo-hab** [comment]
Which boost version do you use?

**Comment by ZhengZhaoHeng** [comment]
It seems that new GPUs like 1080 don't support cudnnv4 anymore. So maybe you could first update caffe in your faster-rcnn folder following the instructions mentioned in [#237](https://github.com/rbgirshick/py-faster-rcnn/issues/237). Then remake your caffe with cudnnv5 and try run the demo again

**Comment by wangha43** [comment]
Well,I have reinstall without cudnn, and it works.

**Comment by dongfeng951** [comment]
I run the caffe code with cudnn v4 on GTX 1080 and have the same problem. But when I run the code on GTX 970, everything is OK.
