### ISSUE TITLE
py-faster-rcnn on dataset with 0...N annotations per image

### ISSUE THREAD

**Issue by sbrugman** [rbgirshick/py-faster-rcnn#338]
While running py-faster-rcnn on images with 0-N (where N is a natural number), the following error occurs:
` BB = BB[sorted_ind, :]`
`IndexError: too many indices for array`

I'm using this script: [inria_eval.py](https://github.com/deboc/py-faster-rcnn/blob/master/lib/datasets/inria_eval.py)
The `detfile` variable is set, but the file is empty. Actually: all files in the /data/[dataset]/results/ directory are empty. Does anyone know if this is a bug or there is a solution for this?

**Comment by sbrugman** [comment]
When I train my model longer - i.e. 1000 iterations instead of 50 - the problem does not occur. Feels to me like the script is not robust enough to work with poor performing networks. Could anyone verify this?

**Comment by pavanteja295** [comment]
I'm referring here to https://github.com/rbgirshick/py-faster-rcnn/ where the same error arises and the reason and the solution for the error is this:

I have seen a lot of posts regarding the error BB = BB[sorted_ind, :] IndexError: too many indices for array which i as well encountered while running the evaluation on a very weakly trained model. I actually found a bug in the file pascal_voc.py which causes this issue.
The all_boxes parameter for the py-faster-rcnn/lib/datasets/pascal_voc.py/evaluate_detection() function in pascal_voc.py is a list of numpy arrays. But in pascal_voc.py/_write_voc_results_file(all_boxes) function in line 251 we check if the

dets == []
but here dets is of type <class 'numpy.ndarray'> and the statement in line 251 evaluates to False leading to consider the empty array being written into the output detection file.

This file with some empty arrays when read in py-faster-rcnn/lib/datasets/eval_voc.py/voc_eval() in line 148 throws and error as BB is just an array.

Solution : In pascal_voc.py/_write_voc_results_file(all_boxes) edit to line 251 should be

dets.tolist() == []

This wont throw the error any more !

Kudos !

**Comment by Flames60** [comment]
> dets.tolist() == []

:
