### ISSUE TITLE
No module named cython_bbox

### ISSUE THREAD

**Issue by SHEKOLDA** [rbgirshick/py-faster-rcnn#351]
Hi, I'm trying to train ZF net on PASCAL VOC 2007 dataset using a CPU-only version on Windows but when initializing the net I'm getting an error:

> ImportError: no module named cython_bbox

I've seen some other issues relative to mine but I haven't found a solution. For example, I tried to follow the solution given here: https://github.com/rbgirshick/fast-rcnn/issues/125 but the error message simply changed to "no module named bbox". Why could this happen? The module is clearly there yet for some reason it cannot be imported.

**Comment by ronilp** [comment]
@SHEKOLDA Did you manage to solve this issue ?

**Comment by SHEKOLDA** [comment]
@ronilp Well kind of. My problem was that i tried to build these modules on Windows and it didn't build correctly so I had to do some trickery with Cython and modify source code a little bit. Frankly, I don't remember what I did exactly, so sorry.

**Comment by xinyifcc** [comment]
Here is my way to solve this error

under your rcnn file     ~/rcnn/

```javascript
# install cython
sudo pip install cython scikit-image easydict
# build cython extension
make
```

**Comment by GrayPlumage** [comment]
For Windows version, I solved it by copy the 3 file folders from
py-faster-rcnn\lib\build\lib.win-amd64-2.7
into
py-faster-rcnn\lib
(After you have installed the setup.py for Windows of course, check https://github.com/MrGF/py-faster-rcnn-windows)

**Comment by silentknight97** [comment]
Hi, above two solutions are not working for me. could any of you guys have another solution for this problem? 
Thanks.
