### ISSUE TITLE
Installing py-faster-rcnn without CUDA (CPU only) on windows

### ISSUE THREAD

**Issue by radhikat** [rbgirshick/py-faster-rcnn#356]
I've been through the issues raised here on installing py-faster-rcnn without cuda and on windows and still can't get it to setup, hence the question here finally. 

1. I removed all instances of cuda from setup.py and other files as instructed on #123 
2. I think I correctly got rid of the MSVCCompiler instance has no attribute 'compiler_so'. by changing the setup.py file to not use the custom_build_ext as this would be a CPU only build on windows #205 
3. Now I have the following error:  
cythoning utils/bbox.pyx to utils\bbox.c
[Errno 2] No such file or directory: ... bbox.pyx'

I have tried all that I could think of, and I still cannot set it up using python .\lib\setup.py build_ext --inplace, any help would  be very much appreciated. 

Also, if I am going about this set up all wrong, knowing that would be helpful too!

Thanks a lot!

**Comment by xjock** [comment]
Why closed the issue? Have you solved the problem?

**Comment by radhikat** [comment]
Yes,I have indeed. py-faster-rcnn still gives me errors when I try to train something, but its nothing to do with the installation but more so with me not having my concepts clear and I am working on that!

**Comment by concerttttt** [comment]
@radhikat can you share the solutions? Facing the same problem now.
