### ISSUE TITLE
Why the output scores of the proposals are almost all the same?

### ISSUE THREAD

**Issue by brisker** [rbgirshick/py-faster-rcnn#362]
![image](https://cloud.githubusercontent.com/assets/13804492/19065018/af0dd602-8a43-11e6-879e-94ea02eb411c.png)
I used my own dataset, with 480 \* 480 size for every image. I used the zf net, after training ,why the scores all all the same?

**Comment by GeorgiAngelov** [comment]
This happened to me but I was getting a lower number. It happened when I tried to tinker with the last FC layers to account for less classes. I have yet to figure out why it is happening.

**Comment by brisker** [comment]
@GeorgiAngelov
So how to fix this?
Did you train faster rcnn with alt_opt or end2end?

**Comment by PANYIMING** [comment]
I have met the same question.So do you know how to fix it now?

**Comment by smajida** [comment]
@brisker @GeorgiAngelov @PANYIMING this is happening to me as well. Previously I had trained with 9 classes with no problem but with 2 classes all of scores are the same.
