### ISSUE TITLE
If my own dataset images are in size 480*480, do I need to modify the rpn_test input size from 224 to 480?

### ISSUE THREAD

**Issue by brisker** [rbgirshick/py-faster-rcnn#363]
name: "ZF"

input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}

input: "im_info"
input_shape {
  dim: 1
  dim: 3
}

**Comment by hgaiser** [comment]
Nope, you can leave that. As far as I am aware, but correct me if I'm wrong ... that 224x224 is just a "placeholder" so that caffe can determine if the input/output of each layer matches up. It will use the 224x224 as an example size image.

**Comment by brisker** [comment]
@hgaiser
I have just finished training, and when I run the demo.py , I found out that all the bounding boxes drawing on the testing image are with a 0.25 confidence, all of them. Why?

**Comment by brisker** [comment]
@hgaiser 
All my images are 480*480 and the object target size is about 25 * 25, should I modify some other parameters?( There is only one class in my dataset, and I have already modify the pascal_voc.py)

**Comment by hgaiser** [comment]
That I don't know ;)

You are using 4 classes? I've seen a similar issue here describing the same thing, there was no solution yet as far as I know. But I see you already found that [issue](https://github.com/rbgirshick/py-faster-rcnn/issues/352#issuecomment-251303176).

From what I can remember you need to adjust the number of classes in your train.prototxt and change the number of bounding box regression output to number_of_classes*4. There is also something related to [number of classes](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/pascal_voc.py#L30-L35) when loading in the dataset.

I believe those were the only adjustments really needed to train on your own dataset. You're sure when you test it, you are using the correct test.prototxt and correct weights?

**Comment by brisker** [comment]
@hgaiser 
I am using 2 classes, and I make sure I have modified all the parameters corresponding to the num classes here:
![image](https://cloud.githubusercontent.com/assets/13804492/19066629/b8b4ce5a-8a4c-11e6-9ecb-b14545da7a5c.png)

**Comment by brisker** [comment]
@hgaiser 

Have you ever used this dataset? http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/

Did you know the meaning of the annotations txt files of this: ?
% bbGt version=3
person-fa 172 184 10 26 0 0 0 0 0 0 0
person-fa 188 188 8 24 0 0 0 0 0 0 0

**Comment by hgaiser** [comment]
Ah you're using alt_opt. I advise to use end2end, it's simpler, faster and gives nearly identical results.

Just to clarify, you've annotated two classes? Do take into account that num_classes should be 3 (your two classes + background). For clarification, here are the lines I remember you need to change:

https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt#L11
https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt#L364
https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt#L444
https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/ZF/faster_rcnn_end2end/train.prototxt#L463
https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/pascal_voc.py#L30-L35


Could be there are more places, not sure.
No, I have never used that dataset.

**Comment by brisker** [comment]
@hgaiser 
Then where to set the max iteration epoch size? I have not found it in the solver.prototxt

**Comment by hgaiser** [comment]
Do you mean [this](https://github.com/rbgirshick/py-faster-rcnn/blob/master/experiments/scripts/faster_rcnn_end2end.sh#L30)?

**Comment by brisker** [comment]
@hgaiser 
Is the /lib/fast_rcnn/config.py 
__C.TRAIN.SCALES = (600,)

# Max pixel size of the longest side of a scaled input image
__C.TRAIN.MAX_SIZE = 1000

600 and 1000 needed to be modified to 480?

**Comment by hgaiser** [comment]
Yeah I think that'd make sense in your case. Basically it will resize your image such that the longest side is 600, limiting the memory that is needed as well. However in your case all your images are smaller than 600.

**Comment by brisker** [comment]
@hgaiser 
What if I only want to train a rpn model to generate proposals? So I must use alt_opt.sh?

**Comment by hgaiser** [comment]
I guess, never worked much with alt_opt.

**Comment by brisker** [comment]
what do you mean? many bugs with alt_opt.sh ?  But I guess I can not train a rpn model with end2end.sh

**Comment by hgaiser** [comment]
end2end fit my needs, it was faster and similar accuracy. If you just need RPN you might need alt_opt or you might need to create your own prototxt to only train RPN.

**Comment by brisker** [comment]
@hgaiser 
error running end2end.sh
im_detect: 28/28 0.052s 0.000s
Evaluating detections
Writing cell VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/fast_rcnn/test.py", line 295, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 318, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 281, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/datasets/voc_eval.py", line 109, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/datasets/voc_eval.py", line 23, in parse_rec
    obj_struct['bbox'] = [int(bbox.find('xmin').text),
ValueError: invalid literal for int() with base 10: '5.2'

**Comment by hgaiser** [comment]
This is when testing the network? Could be because you have some old cache.

**Comment by brisker** [comment]
@hgaiser 
![image](https://cloud.githubusercontent.com/assets/13804492/19067508/266da918-8a51-11e6-9c3f-24278e7e2f2a.png)
yes, when testing the error occurs, but in the data folder only this file

**Comment by brisker** [comment]
@hgaiser 
But surprisingly things change
![image](https://cloud.githubusercontent.com/assets/13804492/19067655/c3db6a46-8a51-11e6-8f6a-aa95e21d1c22.png)

**Comment by brisker** [comment]
@hgaiser 
Thanks for your help.
Besides, if I want to train from scratch, without finetune,  all I need to do is comment the --weights- line?

time ./tools/train_net.py --gpu ${GPU_ID} \
  --solver models/${PT_DIR}/${NET}/faster_rcnn_end2end/solver.prototxt \
  --weights data/imagenet_models/${NET}.v2.caffemodel \
  --imdb ${TRAIN_IMDB} \
  --iters ${ITERS} \

**Comment by CassieMai** [comment]
@brisker  Hello. Did you solve the error ValueError: invalid literal for int() with base 10: '5.2'? I also have this error when testing.

**Comment by Bella722** [comment]
hi,guys, @brisker @hgaiser @CassieMai @rbgirshick i meet the same problem, 
recs[imagename] = parse_rec(annopath.format(imagename))
File "/home/sjtu/code/py-faster-rcnn-master/tools/../lib/datasets/voc_eval.py", line 23, in parse_rec
obj_struct['bbox'] = [int(bbox.find('xmin').text),
ValueError: invalid literal for int() with base 10: '528.4 
how can i solve the error? thank a lot

**Comment by CassieMai** [comment]
@Bella722 Revise int to float32 or float.
