### ISSUE TITLE
How to train a single rpn model? (not faster rcnn)

### ISSUE THREAD

**Issue by brisker** [rbgirshick/py-faster-rcnn#364]
How to train a single rpn model? (not faster rcnn)

**Comment by rohitghosh** [comment]
Hey @brisker, you can have a look at the tools/train_faster_rcnn_alt_opt.py to gain an understanding of how the training is alternated between the RPN & Fast-RCNN. The way the alt_opt works is by:
1. Train RPN 
2. Write down the RPN
3. Train Fast-RCNN using the generated RPNs
Repeat 1-3 again for optimising weights for RPN & Fast-RCNN

So ideally, if you just do steps 1-2 you would be able to generate proposals. To visualise proposals you can check lib/rpn/generate.py which has default visualisation set to 0, you can change to 1, to view the images as well with proposals
