### ISSUE TITLE
How to modify the 4-step training algorithm to learn shared feeatures

### ISSUE THREAD

**Issue by CPFLAME** [rbgirshick/py-faster-rcnn#379]
There are 4 steps during training:
1.fine-tune RPN initialized with pre-trained model
2.fine-tune FAST-RCNN network initialized with pre-trained model
3.use the network in step2 to initialize RPN , and fix the share conv layers,fine-tune RPN
4.keep the share conv layers fixed , fine-tune the fc layers of FAST-RCNN

But now I want to modify step2 ,I want to initialize FAST-RCNN by RPN in step1,which file should I modify?
Thanks : )

**Comment by hgaiser** [comment]
Do you perhaps just want to train end2end? This training scheme is already
available in the repository and it will train RPN and Fast-RCNN
simultaneously.

**Comment by CPFLAME** [comment]
@hgaiser It's so nice of you to reply .As you say,end2end is very similar to the steps I have described. And I have solved this problem by modify  'tools/train_faster_rcnn_alt_opt.py' in the function '___main__'.

**Comment by ymao1993** [comment]
I am curious how well does the modified training protocol work in your case. Do you still remember? @CPFLAME
