### ISSUE TITLE
unstable results for box prediction for 2 class problem?

### ISSUE THREAD

**Issue by hengck23** [rbgirshick/py-faster-rcnn#395]
Hi, I have the following weird results. I make changes to the vgg16 prototxt file to train for 2 class. Here are my train(6) and test images (7):
![data](https://cloud.githubusercontent.com/assets/5112846/19847068/06bf0b6e-9f7f-11e6-9404-a2bf334f7041.jpg)

It run 1000 iterations. The training is normal and the loss decreases as expected. If I disable the box prediction at rcnn (by setting cfg.TEST.BBOX_REG=0), the inference results are ok. But if I use cfg.TEST.BBOX_REG=1, the results are wrong. Please see attachment images.

Can anyone advise what is wrong?
![inference](https://cloud.githubusercontent.com/assets/5112846/19847173/e6224e60-9f7f-11e6-8118-f760296ca020.jpg)

**Comment by frankmanbb** [comment]
have you solveed the problem? I have meet the same problem with 2 classes training. If both of us have such problem, maybe there is a bug with training of two classes.

**Comment by frankmanbb** [comment]
I think I've found the result from here #365 . Since in py faster rcnn, it snapshot its own model by adjusting the layer named bbox_pred. So make sure when testing, use the model saved by this snapshot function. Besides, make sure your layer name is bbox_pred, don't change it to other names ( I change it to other names, so I got abnormal regression bbox)

**Comment by northeastsquare** [comment]
change line:box_deltas = blobs_out['bbox_pred_car'] in lib/fast_rcnn/test.py to following will work:
box_deltas = blobs_out['bbox_pred_car']*np.array([0.1,  0.1,  0.2,  0.2,0.1,  0.1,  0.2,  0.2]

**Comment by hengck23** [comment]
@northeastsquare  @frankmanbb

I think I know the reason. The original faster-rcnn runs like this
1. proposal network rpn:  two-class (object vs background), bbox does **not** use target normalisation
2. rcnn: 21 class (e.g. person vs dog vs cat ... vs background), bbox uses target normalisation

Now we are doing two class problem and hence in the rpn, it is actually doing person vs background already. "No target normalization" may already work quite well in the rpn and hence the default normalization std values for bbox estimation in rcnn training is incorrect.

**Comment by hengck23** [comment]
@northeastsquare @frankmanbb

I check my code again.  Your point is correct and this is the reason. Thanks!

"So make sure when testing, use the model saved by this snapshot function. Besides, make sure your layer name is bbox_pred, don't change it to other names"
