### ISSUE TITLE
Selective search needed for end-to-end training?

### ISSUE THREAD

**Issue by FangLinHe** [rbgirshick/py-faster-rcnn#40]
Hello,

I have just tried the recently updated end-to-end training, but it seems that the selective search pre-computed results are needed during training.  Has anyone tried end-to-end without selective search?  I have modified the code before to tailor my own dataset, and I have traced it to see if I modified anything related, but found nothing helpful.  Any suggestions?  Thank you in advance.

**Comment by peternara** [comment]
need not~~!!

**Comment by FangLinHe** [comment]
Got it and thanks!  I would check my code to see what may cause the problem...
