### ISSUE TITLE
Faster R-CNN with CaffeNet not working

### ISSUE THREAD

**Issue by gombru** [rbgirshick/py-faster-rcnn#405]
Hello,

I'm working with the train_net.py, that is the Fast R-CNN implementation of this Faster R-CNN repository.
I have successfully trained the models given with Faster R-CNN VGG16 and ZF. However, when I try to train the CaffeModel given with Fast R-CNN, I get the following error:

`  File "/home/rgomez/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 135, in setup
    top[idx].reshape(1, self._num_classes * 4)
IndexError: Index out of range`

I'm very interested in train CaffeModel and I cannot use former Fast-CNN code because it is not compatible with my setup. Any ideas?

**Comment by gombru** [comment]
I have already solved the issue. The problem is that Faster R-CNN version uses two bbox weights inputs in data layer: bbox_inside_weights and bbox_outside_weights, while in the CaffeNet of Fast R-CNN is only defined one: bbox_loss weights. That should be changed in the CaffeNet train.prototxt.

**Comment by leekinpo** [comment]
Hello @gombru , I meet the same problem with you, can you post how you changed train.prototxt. is it the one in ./models dir ? Thank you.
