### ISSUE TITLE
How to generate annotation files

### ISSUE THREAD

**Issue by RyoKawauchi** [rbgirshick/py-faster-rcnn#407]
Hi all,
I want to training py-faster-rcnn on my own images.
But I don't know how to generate annotation files because I'm new.
Could anyone explain how to make that?

**Comment by ivanprado** [comment]
Use https://github.com/tzutalin/labelImg to annotate images. Follow the same files structure that PascalVOC20 follows.

**Comment by RyoKawauchi** [comment]
Thanks @ivanprado !
I'll try your great software tomorrow! (because now is midnight in my country...)
