### ISSUE TITLE
All Scores are the same

### ISSUE THREAD

**Issue by rtgoring** [rbgirshick/py-faster-rcnn#417]
It doesn't matter whether it was a model I trained, or a downloaded model all scores are identical. The score is 1/Num_classes. I.E Looking for 21 classes (20+background) all objects have a score of 0.047619

Any ideas?

**Comment by PANYIMING** [comment]
i have met the same question.So have you solved this problem.

**Comment by rtgoring** [comment]
Unfortunately not. I switched to a different Window's port, and the issue went away.

**Comment by smajida** [comment]
@PANYIMING @rtgoring  This is happenning to me as well. Have you fixed it?

**Comment by metehandoyran** [comment]
I had the same issue, and found out the problem was because of a wrong weights .caffemodel file. I recommend you to check the size of your weights file, because it was 0 bytes in my case.

**Comment by 12erCodebohrer** [comment]
@metehandoyran I have the same issue, even the score values of 0.047619 are identical. Can you please be more specific about your solution? Thank you.

**Comment by rtgoring** [comment]
It's been a while so sorry I can't remember details... I ended up switching
to a different version, of faster rcnn or caffe. Not sure which one, but I
remember that there was no fix. Guessing over time layers and parameters
changed, and this is what happens when they don't line up.
