### ISSUE TITLE
train the VOC2007 datasets with the problem 'AttributeError: can't set attribute'

### ISSUE THREAD

**Issue by junedgar** [rbgirshick/py-faster-rcnn#421]
hi all,
    when i tried to train the data i got the error below. using the ZF or VGG16 model had the some problem. Did someboby encounter the some problem?
`I120119:32:07.056460`  2056 layer_factory.hpp:77] Creating layer input-data
I1201 19:32:07.067070  2056 net.cpp:100] Creating Layer input-data
I1201 19:32:07.067133  2056 net.cpp:408] input-data -> data
I1201 19:32:07.067167  2056 net.cpp:408] input-data -> im_info
I1201 19:32:07.067188  2056 net.cpp:408] input-data -> gt_boxes
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/data/zhengjunjun/deeplearning/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/data/zhengjunjun/deeplearning/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 43, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
AttributeError: can't set attribute`

**Comment by baristahell** [comment]
Hey @junedgar 
I'm trying to train faster-RCNN with a custom dataset and encounter this error. Did you manage to solve it? 
Thanks

My error is exactly the same:  

>I0324 15:41:08.419790  5348 layer_factory.hpp:77] Creating layer input-data
>I0324 15:41:08.424814  5348 net.cpp:84] Creating Layer input-data
>I0324 15:41:08.424827  5348 net.cpp:380] input-data -> data
>I0324 15:41:08.424835  5348 net.cpp:380] input-data -> im_info
>I0324 15:41:08.424839  5348 net.cpp:380] input-data -> gt_boxes
>Traceback (most recent call last):
>  File "./tools/train_net.py", line 112, in <module>
>   max_iters=args.max_iters)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 158, in train_net
>    pretrained_model=pretrained_model)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 44, in __init__
>    self.solver = caffe.SGDSolver(solver_prototxt)
>AttributeError: can't set attribute
