### ISSUE TITLE
Link to slides explaining approximate joint training is broken

### ISSUE THREAD

**Issue by chunyang** [rbgirshick/py-faster-rcnn#43]
The link to slides in README.md lands on a 404 page:
https://www.dropbox.com/s/gpvbaf9o4et9d5v/iccv15_tutorial_training_faster.pdf?dl=0

**Comment by rbgirshick** [comment]
Fixed. Here's the correct link: https://www.dropbox.com/s/xtr4yd4i5e0vw8g/iccv15_tutorial_training_rbg.pdf?dl=0.
