### ISSUE TITLE
How to train Faster R-CNN on the 'val' dataset instead of the 'trainval'?

### ISSUE THREAD

**Issue by Johere** [rbgirshick/py-faster-rcnn#440]
There are 4 sets in my own data: 'train' 'val' 'trainval' 'test'. But when I use the py_faster_rcnn, I can only find that it uses 'trainval'. Now I want to use 'train' and 'val' Separately so that I can find the best iteration. Can anyone help me to solve this problem? Thank you very much!

**Comment by Seanmatthews** [comment]
What was your solution? Perchance, do you know if it's possible to train and test on the same dataset?
