### ISSUE TITLE
Cython Modules make issue

### ISSUE THREAD

**Issue by eonurk** [rbgirshick/py-faster-rcnn#446]
I try to make the cython modules and I got the following error

unable to execute '/usr/local/cuda/bin/nvcc': Exec format error
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
make: *** [all] Error 1

Can anybody help?

**Comment by howard0su** [comment]
either file is corrupt or you are trying to run file which is not for your platform. like arm v.s. x86, or x64 v.s. x32
