### ISSUE TITLE
Broken dropbox link to the slides

### ISSUE THREAD

**Issue by JollyGreen** [rbgirshick/py-faster-rcnn#45]
Hello, it looks like the link to your slides in the README.md file is broken.  Would you happen to have an updated link?

https://www.dropbox.com/s/gpvbaf9o4et9d5v/iccv15_tutorial_training_faster.pdf?dl=0

**Comment by rbgirshick** [comment]
Fixed. Here's the correct link: https://www.dropbox.com/s/xtr4yd4i5e0vw8g/iccv15_tutorial_training_rbg.pdf?dl=0.

**Comment by joyyang1215** [comment]
Is it the correct link for now?
