### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by Esugi8** [rbgirshick/py-faster-rcnn#480]
For training ZF Faster-rcnn with PASCAL VOC 2007 dataset, 
I input the command as shown in the tutorial
**./experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc**

Then I got an error below

Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "~ /py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "~ /py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "~ /py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 66, in forward
    rois_per_image, self._num_classes)
  File "~ /py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 191, in _sample_rois
    _get_bbox_regression_labels(bbox_target_data, num_classes)
  File "~ /py-faster-rcnn/tools/../lib/rpn/proposal_target_layer.py", line 127, in _get_bbox_regression_labels
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
**TypeError: slice indices must be integers or None or have an __index__ method**

I just followed the tutorial and did not edit any file.
Could you please let me know how to solve this issue?

--using software versions--
python2.7, Cuda-7.0, cuDNN4.0,

**Comment by bjornamr** [comment]
Got the same error.

**Comment by SietseHuisman** [comment]
Same here. Checked train.prototxt, checked all annotations in my data..

**Comment by alexdominguez09** [comment]
I had exactly the same error message. Solved by uninstalling numpy 1.12.0 and installing numpy 1.11.2.

Worked perfect for me.

**Comment by Esugi8** [comment]
I really appreciate you all giving good advices.
I uninstalled numpy1.12.0, then installed numpy 1.11.1 and re-installed openCV2.4.13, matplotlib1.5.1.
As a result, all issues have been solved!!

**Comment by leejaymin** [comment]
Thanks.
1.10 numpy, that's ok

**Comment by tejus-gupta** [comment]
An easier solution is to add the following lines to ```lib/proposal_target_layer.py```
After line 126,
```
start=int(start)
end=int(end)
```

After line 166,
```
fg_rois_per_this_image=int(fg_rois_per_this_image)
```

**Comment by Po-Hsuan-Huang** [comment]
I can confirm @tejus-gupta 's method worked on numpy 1.12.1.
I was running 
`./tools/train_net.py --gpu 0 --solver models/pvanet/example_finetune/solver.prototxt --weights models/pvanet/pva9.1/PVA9.1_ImgNet_COCO_VOC0712.caffemodel --iters 100000 --cfg models/pvanet/cfgs/train.yml --imdb voc_2007_trainval`

**Comment by zhcf** [comment]
Meet the same problem, fix it using tejus-gupta's suggestion, it worked.

**Comment by sdews** [comment]
I tried to downgrade numpy to version 1.11.2. But there was a new error
`ImportError: numpy.core.multiarray failed to import. `
I tried to solve this new error and failed. Finally, I upgrade numpy to the latest version 1.13.1 . And with @tejus-gupta 's method, I solve the error 
`TypeError: slice indices must be integers or None or have an index method.`

**Comment by Xinying666** [comment]
the same problem
I tried to downgrade numpy to version 1.11.2. But there was a new error
ImportError: numpy.core.multiarray failed to import.
I tried to solve this new error and failed. Finally, I upgrade numpy to the latest version 1.13.1 . And with @tejus-gupta 's method, I solve the error
TypeError: slice indices must be integers or None or have an index method.

**Comment by ShanQincheng** [comment]
the same as @sdews ,but I there is one thing different.

My `proposal_target_layer.py` directory position is at lib/rcn/proposal_target_layer.py

**Comment by Fung-yuantao** [comment]
@tejus-gupta 's method worked. Huge thanks.
But I think it's better to reference the exact line code rather than line number, since the the line number mentioned does not match the one I have. And in my case, `lib/proposal_target_layer.py` should be `lib/rpn/proposal_target_layer.py`.
In code block,

```python
    for ind in inds:
        cls = clss[ind]
        start = 4 * cls
        end = start + 4
        bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
        bbox_inside_weights[ind, start:end] = cfg.TRAIN.BBOX_INSIDE_WEIGHTS
```

add the following two lines after `end = start + 4`,

```python
        start = int(start)
        end = int(end)
```

Add line `fg_rois_per_this_image = int(fg_rois_per_this_image)` after code block,

```python
    # Guard against the case when an image has fewer than fg_rois_per_image
    # foreground RoIs
    fg_rois_per_this_image = min(fg_rois_per_image, fg_inds.size)
```

**Comment by tacsam1212** [comment]
@Fung-yuantao I am new to Python and new to Github so straightaway, I apologize for the lack of the formatting standard. I am having this same issue as above, and am using numpy 1.14.0. However I can't find where the code is I need to add that you mentioned above. Basically, I can't find lib/rpn/proposal_target_layer.py. Could you explain how to find it? 

Here is my error message:

TypeError                                 Traceback (most recent call last)
<ipython-input-22-f86f158851de> in <module>()
----> 1 spectrogram = violin.make_spectrogram(seg_length=1024)
      2 spectrogram.plot(high=5000)

~\Anaconda3\lib\site-packages\thinkdsp.py in make_spectrogram(self, seg_length, win_flag)
    941 
    942         while j < len(self.ys):
--> 943             segment = self.slice(i, j)
    944             if win_flag:
    945                 segment.window(window)

~\Anaconda3\lib\site-packages\thinkdsp.py in slice(self, i, j)
    895         j: second slice index
    896         """
--> 897         ys = self.ys[i:j].copy()
    898         ts = self.ts[i:j].copy()
    899         return Wave(ys, ts, self.framerate)

TypeError: slice indices must be integers or None or have an __index__ method

**Comment by fengyuentau** [comment]
@tacsam1212 Assuming that you are using the up-to-date `py-faster-rcnn`, the file is located in `py-faster-rcnn/lib/rpn/` as the following picture. Or you can use `find` command to search for it on Linux.
![image](https://user-images.githubusercontent.com/17219438/41523805-d7addb34-730d-11e8-976a-a44eb76b1c98.png)

**But** I think what your are dealing with is another project , which is not `py-faster-rcnn`, and for sure you cannot find that file. Errors you got are similar though. You should really read the last part in your error message. Guess `j` is other type like `float`, but **the type of index in `numpy 1.14.0` must be integer**. Maybe you should turn type of `j` to be integer before you are using it as index.

**Comment by tacsam1212** [comment]
@Fung-yuantao I don't see how/where to change the type. Here is the code from where it is saying the error is originating from:


 
    def make_spectrogram(self, seg_length, win_flag=True):
        """Computes the spectrogram of the wave.

        seg_length: number of samples in each segment
        win_flag: boolean, whether to apply hamming window to each segment

        returns: Spectrogram
        """
        if win_flag:
            window = np.hamming(seg_length)
        i, j = 0, seg_length
        step = seg_length // 2

        # map from time to Spectrum
        spec_map = {}

        while j < len(self.ys):
            segment = self.slice(i, j)
            if win_flag:
                segment.window(window)

            # the nominal time for this segment is the midpoint
            t = (segment.start + segment.end) / 2
            spec_map[t] = segment.make_spectrum()

            i += step
            j += step
            
        return Spectrogram(spec_map, seg_length)


**And the second: Lines 891 - 900**

    def slice(self, i, j):
        """Makes a slice from a Wave.

        i: first slice index
        j: second slice index
        """
        ys = self.ys[i:j].copy()
        ts = self.ts[i:j].copy()
        
        return Wave(ys, ts, self.framerate)


How do you change the type of index?

Thanks in advance

**Comment by fengyuentau** [comment]
@tacsam1212 In `slice`, change type of `j` like the following:
```python
def slice(self, i, j):
    """Makes a slice from a Wave.

    i: first slice index
    j: second slice index
    """
    j = (int) j # Change type of j to be integer
    ys = self.ys[i:j].copy()
    ts = self.ts[i:j].copy()
    
    return Wave(ys, ts, self.framerate)
```

**Comment by rh01** [comment]
> @SietseHuisman has identified the error correctly(numpy v1.12.0 doesn't support float indices)
> 
> An easier solution is to add the following lines to `lib/proposal_target_layer.py`
> After line 126,
> 
> ```
> start=int(start)
> end=int(end)
> ```
> 
> After line 166,
> 
> ```
> fg_rois_per_this_image=int(fg_rois_per_this_image)
> ```

 @tejus-gupta 's method worked on numpy 1.16.

**Comment by JorgeYama** [comment]
> @Fung-yuantao 
I found the way to fix it without chaging the version of numpy
First you must know the directory of the file with the error: 
In my case: C:\Users\yamaj\AppData\Local\Programs\Python\Python310\Lib\site-packages\thinkdsp.py
Inside the file .py you must change the following

```
def slice(self, i, j):
    """Makes a slice from a Wave.

    i: first slice index
    j: second slice index
    """
    j = int(j) # Change type of j to be integer
    i = int(i)

    ys = self.ys[i:j].copy()
    ts = self.ts[i:j].copy()
    
    return Wave(ys, ts, self.framerate)

```
and also you must add the same in the first part

```
def make_spectrogram(self, seg_length, win_flag=True):
    """Computes the spectrogram of the wave.

    seg_length: number of samples in each segment
    win_flag: boolean, whether to apply hamming window to each segment

    returns: Spectrogram
    """
    if win_flag:
        window = np.hamming(seg_length)
    i, j = 0, seg_length
    step = seg_length // 2

    # map from time to Spectrum
    spec_map = {}

    while j < len(self.ys):
        j = int(j)
        i = int(i)
        segment = self.slice(i, j)
        if win_flag:
            segment.window(window)

        # the nominal time for this segment is the midpoint
        t = (segment.start + segment.end) / 2
        spec_map[t] = segment.make_spectrum()

        i += step
        j += step
        
    return Spectrogram(spec_map, seg_length)
```

And then, it worked perfectly
