### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by ssieges** [rbgirshick/py-faster-rcnn#481]
I am hitting an error when following the tutorial linked below, which uses the INRIA Person dataset as an example.

https://github.com/deboc/py-faster-rcnn/tree/master/help

Everything seems to be working, but after two hours I keep hitting the following error at Process 3:

Solving...
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 236, in train_fast_rcnn
    max_iters=max_iters
  File "/home/scott/code/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 185, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/scott/code/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 112, in train_model
    self.solver.step(1)
  File "/home/scott/code/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 155, in forward
    blobs = self._get_next_minibatch()
  File "/home/scott/code/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 68, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/scott/code/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 64, in get_minibatch
    num_classes)
  File "/home/scott/code/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 110, in _sample_rois
    fg_inds, size=fg_rois_per_this_image, replace=False
  File "mtrand.pyx", line 1176, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18822)
TypeError: 'numpy.float64' object cannot be interpreted as an index

Does anyone know what might be causing this problem?

**Comment by Microos** [comment]
Same problem! Should expect int type. Still working on it...

**Comment by PentaHiggs** [comment]
Yes, the ability to use floating point indices was deprecated for a bit; It was finally removed in 1.12.  You can also fix the problem by modifying lib/roi_data_layer/minibatch.py

On line 26, there's a call to np.round
fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)
This, unfortunately, creates a float, which causes the issues.  Chaning this line to
 fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image).astype(np.int)
will fix this without having to use an older version of numpy,  since fg_rois_per_image is where the floats were creeping in and causing trouble.  

I believe there are only 3 other places where floats are being used to index, so you'd have to add
.astype(np.int) to the end of

lib/datasets/ds_utils.py line 12 : hashes = np.round(boxes * scale).dot(v)
lib/fast_rcnn/test.py line 129 : hashes = np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v)
 lib/rpn/proposal_target_layer.py line 60 :  fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)

I guess if you're really bored you can sniff out any remaining problematic float indexing attempts, or if you're not then maybe yes, you should install numpy 1.11.0 as suggested above!

**Comment by DavidSPumpkins** [comment]
There seems to be a similar error caused by line 173 in lib/roi_data_layer/minibatch.py.
cls = clss[ind]
This is then used to slice bbox_targets[], however it is not an int and throws an error after hours of training. Change it to,
cls = int(clss[ind])
You will save yourself a headache.

**Comment by ssieges** [comment]
Thanks that fixed it!

**Comment by ManningZhang** [comment]
@PentaHiggs Thanks a lot!! your solution works well, my questions were fixed.

**Comment by sulth** [comment]
Iam having the same error.i tried to resolve error with numpy version as :
      a)version 1.13—>index not an int
      b)downgraded it to 1.11 —>unable to import multi array.How to resolveit now.

**Comment by sulth** [comment]
@PentaHiggs & @DavidSPumpkins Thanks!! It worked i think .The training is not complete though.Thanks.

**Comment by tzrtzr000** [comment]
@sulth Hey I have same problem` (ImportError: numpy.core.multiarray failed to import)` after downgrading to 1.11. How did you figure it out?

**Comment by tzrtzr000** [comment]
Hey @sulth
 I have the same problem (`ImportError: numpy.core.multiarray failed to import`) after downgrading to 1.11. How did you figure it out? Thanks!

**Comment by DavidSPumpkins** [comment]
@tzrtzr000 I try upgrading to numpy 1.13 and solve the "index not an int" problem, as described earlier in this thread.

**Comment by yanxp** [comment]
@tzrtzr000 @sulth  Have you solved the problem?

**Comment by sulth** [comment]
yes .I followed @PentaHiggs & @DavidSPumpkins .It really helped .

**Comment by tzrtzr000** [comment]
@yanxp Yes. For me, I adopted @PentaHiggs' solution : )

**Comment by Xinying666** [comment]
@tzrtzr000 I have the same problem (ImportError: numpy.core.multiarray failed to import) after downgrading to 1.11. How did you figure it out? Thanks!

**Comment by tzrtzr000** [comment]
@Xinying666 try solution provided by @PentaHiggs above

**Comment by Xinying666** [comment]
@tzrtzr000 I tried，but no work for me

**Comment by huangbo1221** [comment]
If you have the same error, you'd better check this sentence: fg_inds = npr.choice(
                fg_inds, size=fg_rois_per_this_image, replace=False) .It's in the py-faster-rcnn/lib/roi_data_layer/minibatch.py. Maybe the type of fg_rois_per_this_image is numpy.float64 and will cause the same error.

**Comment by oguzhantogay** [comment]
I cannot locate roi_data_layer/minibatch.py under Lib. Is there any other solutions that I can try for this problem? I am using python from anaconda 3.6.

`  File "C:\Python3.6\lib\site-packages\numpy\core\fromnumeric.py", line 2317, in amax
    return amax(axis=axis, out=out, **kwargs)`

  `File "C:\Python3.6\lib\site-packages\numpy\core\_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)`
`TypeError: 'numpy.float64' object cannot be interpreted as an integer`

**Comment by ghost** [comment]
Compiled changes necessary for proper integer slicing.
Change the following lines to resolve floating number indexing issue:

```
lib/roi_data_layer/minibatch.py line 26: 
fg_rois_per_image = int(np.round(cfg.TRAIN.FG_FRACTION * rois_per_image))
```
```
lib/datasets/ds_utils.py line 12 : 
hashes = int(np.round(boxes * scale).dot(v))
```
```
lib/fast_rcnn/test.py line 129 : 
hashes = int(np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v))
```
```
lib/rpn/proposal_target_layer.py line 60 : 
fg_rois_per_image = int(np.round(cfg.TRAIN.FG_FRACTION * rois_per_image))
```
```
lib/roi_data_layer/minibatch.py line 173: 
cls = int(clss[ind])
```
```
lib/rpn/proposal_target_layer.py line 124: 
cls = int(clss[ind])
```

**Comment by thepaulm** [comment]
> Yes, the ability to use floating point indices was deprecated for a bit; It was finally removed in 1.12. You can also fix the problem by modifying lib/roi_data_layer/minibatch.py
> 
> On line 26, there's a call to np.round
> fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)
> This, unfortunately, creates a float, which causes the issues. Chaning this line to
> fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image).astype(np.int)
> will fix this without having to use an older version of numpy, since fg_rois_per_image is where the floats were creeping in and causing trouble.
> 
> I believe there are only 3 other places where floats are being used to index, so you'd have to add
> .astype(np.int) to the end of
> 
> lib/datasets/ds_utils.py line 12 : hashes = np.round(boxes * scale).dot(v)
> lib/fast_rcnn/test.py line 129 : hashes = np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v)
> lib/rpn/proposal_target_layer.py line 60 : fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)
> 
> I guess if you're really bored you can sniff out any remaining problematic float indexing attempts, or if you're not then maybe yes, you should install numpy 1.11.0 as suggested above!

Thanks @PentaHiggs!
Why are we not submitting these back as patches? I just went through this same debugging cycle :(

**Comment by jundeli** [comment]
i tried the suggested solutions of downgrading numpy and adding .astype(np.int). But they cannot solve my same error ''numpy.float64' object cannot be interpreted as an integer'. Anyone encounters the same case with me?

**Comment by bosonbeard** [comment]
A have the same error

```
  File "/home/bosonbeard/anaconda3/envs/TOD15/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by MC-devel-staudt** [comment]
@bosonbeard You are trying to use a float, namely a numpy.float, as an index. But that index needs to an int. So you need to cast the num from a float to an int.
`int(num)`
Assuming all other things are correct, this should work.

**Comment by KoraVarisha** [comment]
Hi all,
 I'm a python beginner. I am doing my thesis in a climate science project and I have been provided with the script already. While trying to run this I get the error:

'numpy.float64' object cannot be interpreted as an index

 from the following code:

FluxDispMatSmall = np.zeros([5,5])
FluxDispMatSmall[3,2] = 1
FluxDispMat = np.tile(FluxDispMatSmall,[np.floor(len(latitude)/5+1),np.floor(len(longitude)/5)+1])
FluxDispMat = FluxDispMat[:len(latitude),:len(longitude)]

I'm using anaconda 1.9.12 on a Mac. with Python 2.7 
I have been reading about this error, and seems like a way to solve it, is to go back to numpy version 1.11 ? my current numpy version is 1.16 
is there other way to fix this problem?

thanks so much.

**Comment by snsie** [comment]
I don't think the issue would be fixed by changing the numpy version. It seems like a common data type issue that can be easily fixed with type casting. Python is picky about data types and will complain if you use floats to indicate an array index. 

The array expects an integer so (index=5.0;  array[index]) wouldn't work but (index=5; array[index]) would.

To fix this error with type casting, just wrap the variable with int() to cast it as an integer. (i.e. index=5.0; array[int(index)]) and (index=int(5.0); array[index]) would both work. The second version would permanently change the index variable type to int.

**Comment by KoraVarisha** [comment]
Snsie

THANK YOU !! .. I got it to work with your help. :) 
Thanks so much for taking the time to reply. Much appreciated.

Have a great day.

**Comment by Himanshu66** [comment]
> Yes, the ability to use floating point indices was deprecated for a bit; It was finally removed in 1.12. You can also fix the problem by modifying lib/roi_data_layer/minibatch.py
> 
> On line 26, there's a call to np.round
> fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)
> This, unfortunately, creates a float, which causes the issues. Chaning this line to
> fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image).astype(np.int)
> will fix this without having to use an older version of numpy, since fg_rois_per_image is where the floats were creeping in and causing trouble.
> 
> I believe there are only 3 other places where floats are being used to index, so you'd have to add
> .astype(np.int) to the end of
> 
> lib/datasets/ds_utils.py line 12 : hashes = np.round(boxes * scale).dot(v)
> lib/fast_rcnn/test.py line 129 : hashes = np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v)
> lib/rpn/proposal_target_layer.py line 60 : fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)
> 
> I guess if you're really bored you can sniff out any remaining problematic float indexing attempts, or if you're not then maybe yes, you should install numpy 1.11.0 as suggested above!

Hey, I hope this will work but i am not able to locate minibatch.py file in my project, can anybody help?
