### ISSUE TITLE
detect all objects in one image as "person"?

### ISSUE THREAD

**Issue by kecaiwu** [rbgirshick/py-faster-rcnn#486]
I want to use the faster rcnn to train a model that only detect "person" class. So i use the pascal voc 2007 dataset, i had changed the code in lib/dataset/pascal_voc.py. I get some models by the faster rcnn. However, the model detect all objects in one image and label them "person", Why?

pascal_voc.py
// 001
self._classes = ('__background__', 'person')
// 002
cls = self._class_to_ind['person']

![figure_5-1](https://cloud.githubusercontent.com/assets/17605639/23006121/fc2b25be-f43a-11e6-93e9-4938490dfecd.png)

**Comment by shoCaffeTeria** [comment]
Hi, kecaiwu

It's weird. I dont know why it happened.

Did you delete the ground truth cache?
I'm sorry I forgot where it was. But the name is like "*_gt_roidb.pkl"

**Comment by kecaiwu** [comment]
The reason is we label all objects in images of pascal voc dataset as "person", by "cls = self._class_to_ind['person']" @shoCaffeTeria
