### ISSUE TITLE
how to generate region proposals with RPN

### ISSUE THREAD

**Issue by wolet** [rbgirshick/py-faster-rcnn#489]
Hello,

I could not figure out how to generate region proposals using ``rpn_generate.py``. Which prototxt and caffemodel files should I point to the script?

I tried different prototxt files under `/models/` and net caffemodel files downloaded with provided script under repo. They all failed.

**Comment by thomasSve** [comment]
I ran the following snippet successfully to generate region proposals: 

`./tools/rpn_generate.py --gpu 0 --def models/pascal_voc/VGG16/faster_rcnn_alt_opt/rpn_test.pt --net data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel --imdb dataset`

**Comment by wolet** [comment]
thanks @thomasSve !
