### ISSUE TITLE
Line 145 error while running demo.py

### ISSUE THREAD

**Issue by AzkaGilani** [rbgirshick/py-faster-rcnn#492]
I am using docker version of py-faster-rcnn. but when i run the demo i get the following error:

Loaded network /home/shahrukhqasim/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
Traceback (most recent call last):
  File "./tools/demo.py", line 145, in <module>
    _, _= im_detect(net, im)
NameError: name 'net' is not defined

how can i resolve this issue?

**Comment by asifmahbub** [comment]
HI AzkaGilani, I'm facing the same problem, how did you solve it??
