### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by AzkaGilani** [rbgirshick/py-faster-rcnn#498]
Hey all, I am following [this](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md) tutorial for training faster-rcnn on another dataset. When i try to run the code, i get following errors:
 Called with args:
Namespace(cfg_file='./models/config.yml', gpu_id=0, imdb_name='inria_train', net_name='INRIA_Person', pretrained_model='data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel', set_cfgs=None)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Stage 1 RPN, init from ImageNet model
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Init model: data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel
Using config:
{'DATA_DIR': '/home/shahrukhqasim/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '$PY_FASTER_RCNN/models',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/shahrukhqasim/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': False,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': False,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': 'stage1',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Loaded dataset `train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Process Process-1:
Traceback (most recent call last):
  **File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 122, in train_rpn
    roidb, imdb = get_roidb(imdb_name)
  File "./tools/train_faster_rcnn_alt_opt.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/shahrukhqasim/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/shahrukhqasim/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 104, in append_flipped_images
    widths = self._get_widths()
  File "/home/shahrukhqasim/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 100, in _get_widths
    for i in xrange(self.num_images)]
  File "/home/shahrukhqasim/py-faster-rcnn/tools/../lib/datasets/inria.py", line 47, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/shahrukhqasim/py-faster-rcnn/tools/../lib/datasets/inria.py", line 60, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: ./data/unlv_tables/data/Images/﻿0101_003.pn**

I have debugged and found out that image_path_from_index while making directory path, appends empty space and special charachters in my path. How can i resolve this?

**Comment by Ram-Godavarthi** [comment]
@AzkaGilani Did you solve the problem?? I also got the same error. Someone know how to solve this??
