### ISSUE TITLE
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 350:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".

### ISSUE THREAD

**Issue by IvyGongoogle** [rbgirshick/py-faster-rcnn#500]
hello,when I run 'tools/demo.py', I get the error
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 350:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param". WARNING: Logging before InitGoogleLogging() is written to STDERR F0222 14:23:16.447522 29479 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/xxx/objectDetectionAndRecognition/py-faster-rcnn/models/pascal_voc/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt *** Check failure stack trace: ***
how to solve this error?
thankyou very much!

**Comment by zht3344** [comment]
@IvyGongoogle  I meet the same error, how do you solve this problem?  thank you

**Comment by IvyGongoogle** [comment]
@zht3344  Please google the error above. you can find the answer easily. good luck~
