### ISSUE TITLE
bbox_transform_inv function in bbox_transform.py may contain a tiny bug

### ISSUE THREAD

**Issue by Microos** [rbgirshick/py-faster-rcnn#502]
There are 2 functions in `lib/fast_rcnn/ bbox_transform.py`: `bbox_transform` and `bbox_transform_inv`. 
If we get a `delta` from  `bbox_transform` by feeding two identical bboxes, and then use this `delta` and one of two bboxes to feed the `bbox_transform_inv`. We expect a same output as the input since the 2 bboxes are identical and nothing needs to be adjusted. However the `x2` and `y2` of the result `[x1 y1 x2 y2]` are 1 larger than the expectation. So I believe the predicted `x2` and `y2` need to `-1`.

P.S. : After adding `-1`, the performance increases a little (using a same random seed for comparing).

**Comment by EmGarr** [comment]
@Microos why did you close the issue? I totally agree with the bug if the transformations are (0,0,0,0) we should obtain the same outputs.
