### ISSUE TITLE
Has anyone got a working install of py-faster-rcnn on AWS?

### ISSUE THREAD

**Issue by Aidenhjj** [rbgirshick/py-faster-rcnn#508]
I've been trying to install py-faster-rcnn on an AWS g2.2large for a few days now. I keep running into issues with cudnn versions and keep getting "Check failed: error == cudaSuccess (8 vs. 0)  invalid device function" when I run the demo, which I think is something to do with the architecture settings in the Makefile.config.

Has anyone managed to get a working install on AWS? Can they share with me their system image (AMI)?

**Comment by PetreanuAndi** [comment]
i-m also interested in this. Any help will do. From what i found out up until now, AWS g2.2 has a specific nvidia driver working with it, not the 357. Also cuda version 7.0 and cudnn V4 are supposed to work but i can't get any configuration in place :( is 4Gb enough?
