### ISSUE TITLE
roi_pooling_layer.cpp

### ISSUE THREAD

**Issue by athulase** [rbgirshick/py-faster-rcnn#526]
Is there any plan to implement this block in the layer file roi_pooling_layer.cpp ?
void ROIPoolingLayer<Dtype>::Backward_cpu(const vector<Blob<Dtype>*>& top,
      const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom) {
  NOT_IMPLEMENTED;

**Comment by OneDirection9** [comment]
I think it has been implemented since I have rebuild caffe in [windows caffe](https://github.com/Microsoft/caffe).

**Comment by athulase** [comment]
Thank you. I also found it.
