### ISSUE TITLE
MaxBottomBlobs() >= bottom.size() (3 vs. 4) SmoothL1Loss Layer takes at most 3 bottom blob(s) as input

### ISSUE THREAD

**Issue by wait1988** [rbgirshick/py-faster-rcnn#53]
In the file train.txt,there defines a layer:
layer {
  name: "loss_bbox"
  type: "SmoothL1Loss"
  bottom: "bbox_pred"
  bottom: "bbox_targets"
  bottom: 'bbox_inside_weights'
  bottom: 'bbox_outside_weights'
  top: "bbox_loss"
  loss_weight: 1
}
In the class SmoothL1LossLayer,however,it requires 3 inputs not 4:
void SmoothL1LossLayer<Dtype>::LayerSetUp(
  const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top) {
  has_weights_ = (bottom.size() == 3);
}
Therefore,during the trainning process,error occurs:
I0105 14:10:42.388624 14172 net.cpp:479] rpn_loss_bbox <- rpn_bbox_targets
I0105 14:10:42.390648 14172 net.cpp:479] rpn_loss_bbox <- rpn_bbox_inside_weights
I0105 14:10:42.392648 14172 net.cpp:479] rpn_loss_bbox <- rpn_bbox_outside_weights
I0105 14:10:42.395367 14172 net.cpp:435] rpn_loss_bbox -> rpn_loss_bbox
F0105 14:10:42.397392 14172 layer.hpp:384] Check failed: MaxBottomBlobs() >= bottom.size() (3 vs. 4) SmoothL1Loss Layer takes at most 3 bottom blob(s) as input.
*** Check failure stack trace: ***
Anyone knows how to solve this problem?Thks.

**Comment by cike0cop** [comment]
I also have this problem. did you have solve it ?  Thks.

**Comment by TrackingBird** [comment]
Dear sir, how did you finish this  issue, I have meet this error for a long time. Thanks.

**Comment by lxtGH** [comment]
@TrackingBird @cike0cop @wait1988 Have you solve this problem

**Comment by ZhiHuaYin** [comment]
@wait1988 @cike0cop @lxtGH @TrackingBird anybody has fixed this problem?

**Comment by nancymao** [comment]
https://github.com/wait1988
https://github.com/cike0cop
https://github.com/lxtG
https://github.com/TrackingBirdH
https://github.com/ZhiHuaYin
anybody has fixed this problem? WE CAN DISCUSS !!

**Comment by nancymao** [comment]
@wait1988 @cike0cop @TrackingBird @lxtGH @ZhiHuaYin  

anybody has fixed this problem? WE CAN DISCUSS !!
--

**Comment by ZhiHuaYin** [comment]
> @wait1988 @cike0cop @TrackingBird @lxtGH @ZhiHuaYin
> 
> ## anybody has fixed this problem? WE CAN DISCUSS !!

You can try to delete a bottom.

**Comment by zhaozhenchong** [comment]
@wait1988 @TrackingBird @lxtGH @cike0cop @ZhiHuaYin 
anybody has fixed this problem? WE CAN DISCUSS !!
