### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by baristahell** [rbgirshick/py-faster-rcnn#530]
Hello.
I'm trying to use faster-rcnn to train a net on custom data. I created the `custom.py`, `custom_eval.py` files, added an entry to `factory.py`, etc (see https://github.com/rbgirshick/py-faster-rcnn/issues/243#issuecomment-231049797).
But now i have an issue when i execute the training script `faster_rcnn_end2end_custom.sh`, which is the following :

`./experiments/scripts/faster_rcnn_end2end_custom.sh 0 ZF custom`

[...]
>I0327 08:12:18.197342  6422 layer_factory.hpp:77] Creating layer input-data
>I0327 08:12:18.202009  6422 net.cpp:84] Creating Layer input-data
>I0327 08:12:18.202028  6422 net.cpp:380] input-data -> data
>I0327 08:12:18.202039  6422 net.cpp:380] input-data -> im_info
>I0327 08:12:18.202046  6422 net.cpp:380] input-data -> gt_boxes
>Traceback (most recent call last):
>  File "./tools/train_net.py", line 112, in <module>
>    max_iters=args.max_iters)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 158, in train_net
>    pretrained_model=pretrained_model)
>  File "/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 44, in __init__
>    self.solver = caffe.SGDSolver(solver_prototxt)
>AttributeError: can't set attribute

I first had to do the following : https://github.com/rbgirshick/py-faster-rcnn/issues/455 because i had the same `cudnnNaNPropagation_t` error with CUDA 7.5 and cuDNN 5.
Could it be the reason?
If yes, how do i solve this AttributeError issue while patching the #455 problem?

To be precise, i also tried the classic pascal_voc training (`./experiments/scripts/faster_rcnn_end2end.sh 0 ZF pascal_voc`, i just changed `TRAIN_IMDB="voc_2012_train"` instead of 2007 because i don't have the 2007 data) and i get the same issue.

Thank you.

More or less useful info that may make the answers vary: 
- GPU is a GT 640 (sob)
- I'm working in a Docker image built over nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04

**Comment by smichalowski** [comment]
Hi

Did you change include/caffe/layers/python_layer.hpp?
Remove line "self_.attr("phase") = static_cast<int>(this->phase_);" and recompile

**Comment by baristahell** [comment]
Seems like it was a Caffe version issue and the #455 cudnn v5 "patch" was more of a shot in the foot.
Thanks thought.

**Comment by nnop** [comment]
Why the line `self_.attr("phase") = static_cast(this->phase_);` cause the `set attribute error` during runtime? @smichalowski @baristahell
