### ISSUE TITLE
proposal can't set attribute - Windows CPU mode

### ISSUE THREAD

**Issue by Ravisik** [rbgirshick/py-faster-rcnn#531]
Hello everyone! 

I've managed to install py_faster_rcnn in CPU mode with caffe for windows, after many different issues solved caffe seems to work fine with py_frcnn

But I have now this issue when I run demo.py : 
```

I0327 17:57:32.295704 10256 net.cpp:84] Creating Layer proposal
I0327 17:57:32.295704 10256 net.cpp:406] proposal <- rpn_cls_prob_reshape
I0327 17:57:32.296705 10256 net.cpp:406] proposal <- rpn_bbox_pred
I0327 17:57:32.296705 10256 net.cpp:406] proposal <- im_info
I0327 17:57:32.296705 10256 net.cpp:380] proposal -> rois
Traceback (most recent call last):
  File "C:/Users/Manon/PycharmProjects/py-faster-rcnn/tools/demo.py", line 136, in <module>
    net = caffe.Net(prototxt, caffemodel, caffe.TEST)
AttributeError: can't set attribute

Process finished with exit code 1
```

Changing python_layer.hpp seems not to work (as exoised in #249 ) 
thanks in advance,
Flo

**Comment by Ravisik** [comment]
#249

**Comment by loukbabi** [comment]
Hello Ravisik.

I can see that your original title was "ImportError: No module named 'generate_anchors'".
I have the exact same error when I try to run the demo. Did you solve this issue?

Thank you.

**Comment by loukbabi** [comment]
OK. So I just found out how to fix that. I don't know why, but I needed to change the 
"from generate_anchors import generate_anchors" 
line to 
"from rpn.generate_anchors import generate_anchors"
in the lib/rpn/proposal_layer.py file.

Any reason for the above error? Does this mean that something is wrong with my setup?
Thank you anyway.

**Comment by TVXQ20031226** [comment]
@loukbabi hi, i met the same error with you ."ImportError: No module named 'generate_anchors'"
 i tried to use the method you mentioned , but it did not work ! do you find the other way to fix it now??
thank you!!

**Comment by loukbabi** [comment]
Sorry. That was the only way I tried.
