### ISSUE TITLE
Aborted (core dumped) while running demo.py

### ISSUE THREAD

**Issue by saurabhgoyaliitr** [rbgirshick/py-faster-rcnn#538]
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, LRN, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Pooling, Power, ROIPooling, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, SmoothL1Loss, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)
*** Check failure stack trace: ***
Aborted (core dumped)

(I am using CPU only mode .
 --cpu command)

**Comment by sohamghoshmusigma** [comment]
Hi @saurabhgoyaliitr 

Can you tell me how you solved this problem? I'm getting the same error. Although I'm using GPU mode, this would still be helpful to know

**Comment by saurabhgoyaliitr** [comment]
Sure.The error says the python layer is unknown.so set WITH_PYHON_LAYER = 1 in the makeconfig file and then make the caffe files again by first unmaking it(this step is important)

**Comment by sohamghoshmusigma** [comment]
Hi, yeah I did that. Thanks a lot. I get another error though. Did you face this error following this solution?
It goes like
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

**Comment by shehabk** [comment]
@sohamghoshmusigma could you solve this issue ?
