### ISSUE TITLE
Much fewer memory required with end-to-end training!

### ISSUE THREAD

**Issue by FangLinHe** [rbgirshick/py-faster-rcnn#54]
Hi rbgirshick, just want to share with you that, using your awesome end-to-end model, I am able to train the VGG net with only 4GB GPU memory (actually around 3GB is enough).  Probably you could test again the memory requirements for end-to-end model and update it in readme. :) Thanks.

**Comment by rbgirshick** [comment]
Thanks for the feedback!

**Comment by Oh233** [comment]
@FangLinHe Is that due to cudnn instead of the training algorithm? Because it still takes 6.5G to train VGG16 without cuDNN using the default setting. And after I enable cuDNN, it becomes 2.8G.

**Comment by duygusar** [comment]
I can't use cuDNN and the memory is a big problem for me right now even with batch sizes set to 1 and decreased no of proposals. I worked with alternative optimization and didn't have a problem.
