### ISSUE TITLE
INdexError：Too many indices……

### ISSUE THREAD

**Issue by YoWhatever** [rbgirshick/py-faster-rcnn#558]
VGG16 end2end version： correct.
VGG16 alt_opt version: INdexError：Too many indices……
I didn't change any parameter default, and I use the pascal_voc_2007_trainval, can anyone tell me what's wrong?

**Comment by amirhfarzaneh** [comment]
@YoWhatever I have the same problem on both end2end and alt-opt versions. Have you solved it?
