### ISSUE TITLE
How to interpret 'dets' numpy array in demo.py

### ISSUE THREAD

**Issue by hoticevijay** [rbgirshick/py-faster-rcnn#58]
In demo.py there is a variable named dets [ numpy array] which is passed as a parameter to vis_detections() function. 
The dets array has 5 columns all the time and  data from the fifth column is used to filter out the proposals [based on CONF_THRESHOLD]. So is the fifth column on dets, the prediction score for the particular proposed image area?

**Comment by Dectinc** [comment]
the first 4 columns denote xmin, ymin, xmax, ymax respectively, as a bounding box in annotations, and the 5th denotes detection confidence level of a specific class.

snippet in toos/demo.py
```
        inds = np.where(dets[:, -1] >= CONF_THRESH)[0]
        if len(inds) == 0:
            continue

        for i in inds:
            bbox = dets[i, :4]
            score = dets[i, -1]
            ax.add_patch(
                    plt.Rectangle((bbox[0], bbox[1]),
                                  bbox[2] - bbox[0],
                                  bbox[3] - bbox[1], fill=False,
                                  edgecolor='red', linewidth=3.5)
            )
```

**Comment by hoticevijay** [comment]
He thanks for the clarification. I will close this.
