### ISSUE TITLE
Output contains only single class 

### ISSUE THREAD

**Issue by shrishtrived** [rbgirshick/py-faster-rcnn#588]
![004545](https://cloud.githubusercontent.com/assets/28747755/26395816/e5d7a788-408e-11e7-80fe-de43989e439e.jpg)
The output( from demo.py ) only shows single class instead of all class , example in this case above, car and dog are not detected.
Can anyone tell me why?

**Comment by litingsjj** [comment]
Is your CLASSES=('_background_',‘person’)？when my
`CLASSES = ('__background__',
           'aeroplane', 'bicycle', 'bird', 'boat',
           'bottle', 'bus', 'car', 'cat', 'chair',
           'cow', 'diningtable', 'dog', 'horse',
           'motorbike', 'person', 'pottedplant',
           'sheep', 'sofa', 'train', 'tvmonitor')`

```Traceback (most recent call last):
  File "tools/demo_rfcn_face.py", line 185, in <module>
    demo(net, im_name, resultlist)
  File "tools/demo_rfcn_face.py", line 108, in demo
    cls_scores = scores[:, cls_ind]
IndexError: index 2 is out of bounds for axis 1 with size 2
```
Have you solved?
