### ISSUE TITLE
Use new dataset to train faster rcnn

### ISSUE THREAD

**Issue by yaokmallorca** [rbgirshick/py-faster-rcnn#597]
I'm trying to train py-faster-rcnn using my own dataset.

Now, I got error as following:

Loaded dataset `train` for training
Set proposal method: rpn
Appending horizontally-flipped training examples...
train gt roidb loaded from /data/HD1/yaok/py-faster-rcnn/data/cache/train_gt_roidb.pkl
loading /data/HD1/yaok/py-faster-rcnn/output/default/train/vgg_cnn_m_1024_rpn_stage1_iter_80000_proposals.pkl
/usr/lib/python2.7/dist-packages/scipy/sparse/coo.py:182: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) != 2:
/usr/lib/python2.7/dist-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:
/usr/lib/python2.7/dist-packages/scipy/sparse/sputils.py:141: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) == 0 and np.rank(N) == 0:
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py:502: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(blocks) != 2:
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 189, in train_fast_rcnn
    roidb, imdb = get_roidb(imdb_name, rpn_file=rpn_file)
  File "./tools/train_faster_rcnn_alt_opt.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/data/HD1/yaok/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/data/HD1/yaok/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/data/HD1/yaok/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/data/HD1/yaok/py-faster-rcnn/tools/../lib/datasets/inria.py", line 103, in rpn_roidb
    roidb = imdb.merge_roidbs(gt_roidb, rpn_roidb)
  File "/data/HD1/yaok/py-faster-rcnn/tools/../lib/datasets/imdb.py", line 250, in merge_roidbs
    b[i]['gt_overlaps']])
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 454, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 533, in bmat
    raise ValueError('blocks[%d,:] is all None' % brow_lengths.argmin())
ValueError: blocks[0,:] is all None

I follow the tutorial (https://github.com/deboc/py-faster-rcnn/tree/master/help).
Could someone tell me how to solve this?

**Comment by yaokmallorca** [comment]
I modify the imdb.py Line 249 as following:
if np.shape(a[i]['gt_overlaps'])[0] > 0:
	a[i]['gt_overlaps'] = scipy.sparse.vstack([a[i]['gt_overlaps'],
                                                       b[i]['gt_overlaps']])
else:
	a[i]['gt_overlaps'] = b[i]['gt_overlaps']
This mistake disappear.

**Comment by MissDores** [comment]
Hi, yaokmallora, I use your method training on subset of my training data, the error is fixed. But when I trained on my whole dataset, the error appeared once again. Can you help me?
