### ISSUE TITLE
Testing Error using self-trained caffemodel with two calsses of "background" and "car"

### ISSUE THREAD

**Issue by nanzhixiong** [rbgirshick/py-faster-rcnn#629]
![000001](https://user-images.githubusercontent.com/29846964/28107714-7e73f98a-671b-11e7-973a-e72df327bb73.jpg)

As shown in this image, I test the self-trained model on the image and only get some proposal bounding box, and all confidence of the boxes are 0.5. 

Did some have the similar experience?

**Comment by MartinPlantinga** [comment]
Looks like your softmax outputs very low values causing it to yield a uniform distribution.
