### ISSUE TITLE
Modifications for grayscale images

### ISSUE THREAD

**Issue by maxcw** [rbgirshick/py-faster-rcnn#642]
I would like to train and test a model based on grayscale images only, using 1) faster RCNN alternating optimzation and 2) Faster RCNN End2End. What changes do I need to make to the code? For simplicity, assume everything else about the data (number of classes, etc.) is the same as Pascal VOC.

**Comment by zhenni** [comment]
If you need to fine-tune from some popular models which use some image data with color, you may not need to change anything, also for simplicity.
If you really want to change the input...the functions you may need to modify are `setup` in `lib/roi_data_layer/layer.py` and `_get_image_blob` in  `lib/roi_data_layer/minibatch.py`

**Comment by maxcw** [comment]
Thank You! i will first not do anything, for simplicity. And if that doesn't work, I'll look at the files.

**Comment by HilmiK** [comment]
Did you resolve the issue just by doing the steps above?
