### ISSUE TITLE
anchors

### ISSUE THREAD

**Issue by thanasissdr** [rbgirshick/py-faster-rcnn#655]
As mentioned in the original paper, the positive/negative anchor boxes in RPN get a ground truth label 0/1 (object or not object), respectively. Is that the case when we have more classes? What happens in the case where we have `k > 2` classes? I guess in that case each RoI gets also a ground truth class label (something like bird, car, etc.), right? 

As far as I can understand, RPN is used for generating object proposals and then the second module of Faster R-CNN is based on Fast R-CNN. But Fast R-CNN requires that each RoI participating in the training process should have a ground truth class label.

**Comment by ppwwyyxx** [comment]
Only object or not object for RPN.
The second module (fast r-cnn) uses class label.
