### ISSUE TITLE
Cannot create Cublas handle. Cublas won't be available

### ISSUE THREAD

**Issue by zakizadeh** [rbgirshick/py-faster-rcnn#667]
hi . when i run demo,py i have error :
~/py-faster-rcnn$  ./tools/demo.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0825 12:20:57.195098 12256 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
E0825 12:20:57.195904 12256 common.cpp:111] Cannot create Curand generator. Curand won't be available.
F0825 12:20:57.196717 12256 common.cpp:142] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***

**Comment by slprojects** [comment]
I have exactly the same problem.
Does anyone have any information that can help us?

**Comment by zakizadeh** [comment]
read examples in this site : 
https://chunml.github.io/portfolio/

**Comment by DreamFlasher** [comment]
Can you be more specific about the solution? This links to a landing page and no further insight in how to solve this problem.

**Comment by JeromeMutgeert** [comment]
I think this error 'CUDA driver version is insufficient for CUDA runtime version' indicates that the version of the nvidia driver is not high enough for the version of cuda you are using. In this file the requirements are listed (ctrl-F on 'driver'): https://developer.download.nvidia.com/compute/cuda/9.2/Prod/docs/sidebar/CUDA_Toolkit_Release_Notes.pdf

**Comment by zdgithub** [comment]
I have exactly the same problem, could anyone tell me how to solve it? Thank you.

**Comment by yezhengli-Mr9** [comment]
> hi . when i run demo,py i have error :
> ~/py-faster-rcnn$ ./tools/demo.py
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> E0825 12:20:57.195098 12256 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
> E0825 12:20:57.195904 12256 common.cpp:111] Cannot create Curand generator. Curand won't be available.
> F0825 12:20:57.196717 12256 common.cpp:142] Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version
> *** Check failure stack trace: ***

Any tutorial to switch to CPU-only caffe?`caffe.set_mode_cpu()` seems not enough. I am studying [another problem](https://github.com/airsplay/lxmert/issues/89) anyway.
