### ISSUE TITLE
Is py-faster-rcnn surpports the latest caffe?

### ISSUE THREAD

**Issue by leejiajun** [rbgirshick/py-faster-rcnn#68]

**Comment by zyyang** [comment]
yes, you have to port few files(seehttps://github.com/rbgirshick/caffe-fast-rcnn/commit/4115385deb3b907fcd428ac0ab53b694d741a3c4 ) to latest caffe. 
and no, there is a problem with training zf model(weird heavy cpu usage).

**Comment by leejiajun** [comment]
thank you

**Comment by iXce** [comment]
hmm, is there a discussion about the weird cpu usage when training the ZF model ? I'm seeing this right now. thanks !
