### ISSUE TITLE
Training image only has one object, but test image has multiple objects.

### ISSUE THREAD

**Issue by tianzq** [rbgirshick/py-faster-rcnn#705]
My detection task: 400 classes, 10k training images (each image only contains one object), 1k test images( each image contains multiple objects).

If I train a model based on training set that each training image only has one object (class). While the test image has multiple objects (classes). Whether the trained model works in this situation?

**Comment by tianzq** [comment]
I already addressed this issue. It works!

**Comment by Usernamezhx** [comment]
@tianzq hi tianzq. Can you give me the solution about **the test image has multiple objects** thanks

**Comment by tianzq** [comment]
It works for one object training image. But the accuracy is not good.

Multiple objects of training images are recommended.
