### ISSUE TITLE
Error after training and testing on VOC2007, error(message('MATLAB:textread:FileNotFound'));

### ISSUE THREAD

**Issue by smajida** [rbgirshick/py-faster-rcnn#74]
Hi,
I installed py faster rcnn and ran some demo images. then I wanted to train and test the pretrained VGG16 but when it goes into Matlab Program I get the following error:
                                                                                              < M A T L A B (R) >
                                                                                    Copyright 1984-2015 The MathWorks, Inc.
                                                                                    R2015b (8.6.0.267246) 64-bit (glnxa64)
                                                                                                August 20, 2015

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 

	Academic License

aeroplane: pr: load: 75/4952
aeroplane: pr: load: 194/4952
aeroplane: pr: load: 328/4952
aeroplane: pr: load: 516/4952
aeroplane: pr: load: 676/4952
aeroplane: pr: load: 852/4952
aeroplane: pr: load: 1048/4952
aeroplane: pr: load: 1250/4952
aeroplane: pr: load: 1398/4952
aeroplane: pr: load: 1590/4952
aeroplane: pr: load: 1749/4952
aeroplane: pr: load: 1942/4952
aeroplane: pr: load: 2116/4952
aeroplane: pr: load: 2314/4952
aeroplane: pr: load: 2492/4952
aeroplane: pr: load: 2679/4952
aeroplane: pr: load: 2840/4952
aeroplane: pr: load: 3030/4952
aeroplane: pr: load: 3193/4952
aeroplane: pr: load: 3367/4952
aeroplane: pr: load: 3530/4952
aeroplane: pr: load: 3729/4952
aeroplane: pr: load: 3916/4952
aeroplane: pr: load: 4097/4952
aeroplane: pr: load: 4237/4952
aeroplane: pr: load: 4421/4952
aeroplane: pr: load: 4586/4952
aeroplane: pr: load: 4767/4952
aeroplane: pr: load: 4945/4952
Error using textread (line 165)
File not found.

Error in VOCevaldet (line 30)
[ids,confidence,b1,b2,b3,b4]=textread(sprintf(VOCopts.detrespath,id,cls),'%s %f %f %f %f %f');

Error in voc_eval>voc_eval_cls (line 36)
  [recall, prec, ap] = VOCevaldet(VOCopts, comp_id, cls, true);

Error in voc_eval (line 8)
  res(i) = voc_eval_cls(cls, VOCopts, comp_id, output_dir, rm_res);
 
165     error(message('MATLAB:textread:FileNotFound'));
K>>

**Comment by smajida** [comment]
solved.

you should uncomment the line for VOC.detrespath in VOCinit.m for using 'test' as VOC.testset not 'val'

**Comment by ggghh** [comment]
fast_rcnn startup done
GPU 1: free memory 9681179443
Use GPU 1
Error using textread (line 159)
File not found.

Error in imdb_from_voc (line 46)
  imdb.image_ids = textread(sprintf(VOCopts.imgsetpath, image_set), '%s');

Error in Dataset.voc2007_test (line 14)
        dataset.imdb_test     = imdb_from_voc(devkit, 'test', '2007', use_flip) ;

Error in script_faster_rcnn_VOC2007_VGG16 (line 30)
dataset                     = Dataset.voc2007_test(dataset, 'test', false);

I have same problem do you have any idea ?
