### ISSUE TITLE
Problem occured when training py-faster-rcnn on my dataset

### ISSUE THREAD

**Issue by 139419qw** [rbgirshick/py-faster-rcnn#752]
Hello guys.I'm new to py-faster-rcnn.
When I am training on my own dataset,at first,everything seems goes right.But then I have meet this problem:

Normalizing targets
done
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1214 15:32:27.177620 25309 solver.cpp:48] Initializing solver from parameters: 
train_net: "models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt"
base_lr: 0.0001
display: 20
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 1000
snapshot: 0
snapshot_prefix: "zf_fast_rcnn"
average_loss: 100
I1214 15:32:27.177677 25309 solver.cpp:81] Creating training net from train_net file: models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 251:12: Message type "caffe.InnerProductParameter" has no field named "name".
F1214 15:32:27.177844 25309 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/pascal_voc/ZF/faster_rcnn_alt_opt/stage1_fast_rcnn_train.pt

could you please tell me what happened?thanks a lot!

**Comment by MrWanter** [comment]
@139419qw have you solved the problem? I have same problem of `Error parsing text-format caffe.NetParameter: 1:3: Message type "caffe.NetParameter" has no field named "me".`

**Comment by 139419qw** [comment]
@MrWanter Sorry for later reply, I have already solved this problem. Please check your file under py-faster-rcnn/models/pascal_voc/ZF/faster_rcnn_alt_opt(or other model) have been modified to meet your request. I encountered this problem because I forget to modify the faster_rcnn_test.pt.
