### ISSUE TITLE
fetch_fast_rcnn_models

### ISSUE THREAD

**Issue by heatherzheng** [rbgirshick/py-faster-rcnn#760]
I try to do the step below,but jumps out errors. 
cd $FRCN_ROOT
./data/scripts/fetch_fast_rcnn_models.sh

not founds/fetch_faster_rcnn_models.sh: 2: data/scripts/fetch_faster_rcnn_models.sh: 
data/scripts/fetch_faster_rcnn_models.sh: 3: data/scripts/fetch_faster_rcnn_models.sh: Bad substitution
data/scripts/fetch_faster_rcnn_models.sh: 4: cd: can't cd to /
: not founds/fetch_faster_rcnn_models.sh: 5: data/scripts/fetch_faster_rcnn_models.sh: 
: not founds/fetch_faster_rcnn_models.sh: 9: data/scripts/fetch_faster_rcnn_models.sh: 
data/scripts/fetch_faster_rcnn_models.sh: 15: data/scripts/fetch_faster_rcnn_models.sh: Syntax error: "elif" unexpected (expecting "then")

**Comment by pscheich** [comment]
Hey,

take a look at this:
https://github.com/rbgirshick/py-faster-rcnn/issues/755

Have an awesome 2018.

**Comment by Brad-Robbins** [comment]
I think u had a substitution in the code as I see up around 3) that it says "bad substitution", and near the bottom it explains as expecting "then"... which is I suppose the best a computer can do to attempt to point up to the initial error jump.  cross check your code in those spots may be easy.

**Comment by heatherzheng** [comment]
I solved the problem by changing the file to the unix version
