### ISSUE TITLE
How to modify the feat_stirde value？

### ISSUE THREAD

**Issue by Huangswust182** [rbgirshick/py-faster-rcnn#778]
Hello，everybody！
  I have a problem, if I remove the max-pooling layer behind conv3 and conv4, should the value of feat_stride be changed to 4?

  param_str: "'feat_stride': 4"

  I hope you can answer me, thank you.

**Comment by wangxinyu199306** [comment]
yes, and do not forget to change spatial_scale to 0.25(1/4)

**Comment by Huangswust182** [comment]
Thank you for your answer, but after I modified the values of feat_stride and spatial_scale, I made a mistake and couldn't run it.
The error is as follows：
out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
F0128 20:12:00.456166 26367 syncedmem.hpp:22] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered

Do you change these two parameters, please?

**Comment by Huangswust182** [comment]
@wangxinyu199306

**Comment by Huangswust182** [comment]
@wangxinyu199306 
Thank you for your answer, but after I modified the values of feat_stride and spatial_scale, I made a mistake and couldn't run it.
The error is as follows：
out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
F0128 20:12:00.456166 26367 syncedmem.hpp:22] Check failed: error == cudaSuccess (77 vs. 0) an illegal memory access was encountered

Do you change these two parameters, please?

**Comment by wangxinyu199306** [comment]
feat stride is ratio between the last feature map and input image.
generally, the feature map should be kept in a small size, or it will cost too much during region proposal(I mean cost on both computation and memory).
I suppose thats how error happened.

try to increase the feat stride(pooling or increase the stride)

**Comment by Huangswust182** [comment]
@wangxinyu199306 thank you very much
