### ISSUE TITLE
faster-rcnn error no module named fast_rcnn

### ISSUE THREAD

**Issue by HaoWangDL** [rbgirshick/py-faster-rcnn#787]
When I configure faster-rcnn, I modified make.sh and setup.py in accordance with the online tutorials that can be compiled and passed. But when I run demo.py, there are the following errors. GitHub has a similar problem, and it still has the problem after trying it.
My environment configuration is python3.5, tensorflow1.4.1, `ubuntu16.04

`Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from lib.networks.factory import get_network
  File "/home/wangh/anaconda3/lib/python3.5/site-packages/TFFRCNN/lib/__init__.py", line 1, in <module>
    import fast_rcnn
ImportError: No module named 'fast_rcnn'
`

**Comment by LucasMahieu** [comment]
Try to add the lib path to you PYTHONPATH doing:
export PYTHONPATH=path/to/lib:$PYTHONPATH

**Comment by HaoWangDL** [comment]
@LucasMahieu thanks,the problem had been solved
