### ISSUE TITLE
failed in predicting 4 points(x1,y1,x2,y2,x3,y3,x4,y4) to faster rcnn

### ISSUE THREAD

**Issue by arasharchor** [rbgirshick/py-faster-rcnn#789]
Hi, 

I have tried to modify faster rcnn to predict (x1,y1,x2,y2,x3,y3,x4,y4) rather than (xmin,ymin,xmax,ymax). However, when I change the number of RPN network outputs and ROI outputs from 84(4*21 for Pascal VOC with 21 classes) to 168 (8*21) and also modify factory.py and custom-dataset.py in data folder, the network is not able to learn the coordinates and it is not obvious what else should be changed. 

I have modified the pascal-voc.py as below:
```python
for pt in obj.findall('pt'):
            x1 = float(pt.find('x1').text) 
            y1 = float(pt.find('y1').text) 
            x2 = float(pt.find('x2').text) 
            y2 = float(pt.find('y2').text)
            x3 = float(pt.find('x3').text) 
            y3 = float(pt.find('y3').text) 
            x4 = float(pt.find('x4').text) 
            y4 = float(pt.find('y4').text) 
            cls = self._class_to_ind[obj.find('name').text.lower().strip()]
            boxes[ix, :] = [x1, y1, x2, y2, x3, y3, x4, y4]
            gt_classes[ix] = cls
            overlaps[ix, cls] = 1.0
```
and in train.prototxt, the number of rpn outputs were changed from 36(4*9) to 72(8*9).

```
layer {
  name: "rpn_bbox_pred"
  type: "Convolution"
  bottom: "rpn_conv1"
  top: "rpn_bbox_pred"
  param { lr_mult: 1.0 }
  param { lr_mult: 2.0 }
  convolution_param {
    num_output: 72  # 8 * 9(anchors)
    kernel_size: 1 pad: 0 stride: 1
    weight_filler { type: "gaussian" std: 0.01 }
    bias_filler { type: "constant" value: 0 }
  }
}
```

![screenshot from 2018-03-06 23-06-17](https://user-images.githubusercontent.com/12903362/37063374-79e8f76a-2199-11e8-817e-9d17a742b57c.png)

**Comment by HappyKerry** [comment]
@smajida have you solved the problem?
