### ISSUE TITLE
A question about rois sampling

### ISSUE THREAD

**Issue by SingL3** [rbgirshick/py-faster-rcnn#795]
Hello!
I‘ve trained a faster rcnn model in end2end way. However, some of my objects get a right bounding box with low classification score. I doubt it is because the imbalance between objects classes and background class. And when I try to train this model in two  stages way, the result is  better. But I notice that there is no a roi sampling procedure. Is that true?

**Comment by zchrissirhcz** [comment]
Definitely not true.

see `lib/rpn/anchor_target_layer.py`.

Also, see `lib/rpn/proposal_target_layer.py`
