### ISSUE TITLE
Coco support

### ISSUE THREAD

**Issue by rodrigob** [rbgirshick/py-faster-rcnn#82]
Is there any plan of adding training/testing on Ms Coco "out of the box" ?

I noticed a recent commit in this direction.

**Comment by rbgirshick** [comment]
Yeah, I finally going to put out-of-the-box COCO support into master. Hopefully it will land later this week or next week, depending on how testing goes.

**Comment by rodrigob** [comment]
We would love to launch some training this week (ECCV approaching).
Any way we could help ? (fixing something, testing something ?)

Otherwise we might start redundant work by hacking our way starting from [the fast-rcnn coco code]( https://github.com/rbgirshick/fast-rcnn/blob/coco/lib/datasets/coco.py)

**Comment by rbgirshick** [comment]
I'm within hours of pushing the code :). I'm just waiting for some tests to finish.

**Comment by rbgirshick** [comment]
COCO support landed in d66cc2bff142ca07f521db06ca3e9e10dbc8df20. It's not super well tested, so feedback is appreciated!

**Comment by kshitid20** [comment]
Can we train RPN only  on MS COCO? From what I read in the commit we still have to take proposals from MCG,Selective search so I am still not sure how to use coco for alternate training

**Comment by liuchang8am** [comment]
Same question as @kshitid20. Is it possible to train without pre-downloaded proposals?

**Comment by liuchang8am** [comment]
Just checked out that it can train directly, with no need for the proposals. See ./experiments/scripts/faster_rcnn_end2end.sh for details. On K40c I get about 1.3s/iter with default settings. @kshitid20 you may have a look at it.

**Comment by kshitid20** [comment]
@liuchang8am Thanks :),

**Comment by chankim** [comment]
Hi, I'm trying to train ZF for COCO data set. In the git there's no models/coco/ZF directory, I copied files under models/pascal_voc/ZF to there and ran the experiments/scripts/faster_rcnn_end2end.sh 0 ZF coco but seeing some errors. @rbgirshick Can you please check COCO-ZF training ad upload it?

**Comment by chankim** [comment]
I opened an issue #305, I posted a message there copy it here just so any one can see my message.
I had an error saying bottom[0]->num() ==2 but bottom[1]->num() ==1 at rpn_cls_loss layer before.
-------------
It was because num is set to 2 from the data-input layer. So in lib/fast_rcnn/config.py, I set `cfg.TRAIN.IMS_PER_BATCH = 1`. And to avoid errors, I also set `__C.TRAIN.BBOX_NORMALIZE_TARGETS_PRECOMPUTED = True` and having realized that  there are only 3 top blobs from the input-data layer, I set `__C.TRAIN.HAS_RPN = True` and `__C.TEST.HAS_RPN = True`.  When I run it using command `experiments/scripts/faster_rcnn_end2end.sh 0 ZF coco --set RNG_SEED 42 TRAIN.SCALES "[400,500,600,700]"` the final error is :   
```
Solving...
I0830 21:40:59.412508 19977 net.cpp:602] ## : net_input_blobs_.size() : 0
I0830 21:40:59.646147 19977 net.cpp:602] ## : net_input_blobs_.size() : 0
Traceback (most recent call last):
  File "./tools/train_net_e2e.py", line 114, in <module>
    max_iters=args.max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/rpn/proposal_target_layer.py", line 66, in forward
    rois_per_image, self._num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/rpn/proposal_target_layer.py", line 191, in _sample_rois
    _get_bbox_regression_labels(bbox_target_data, num_classes)
  File "/home/ckim/Neuro/py-faster-rcnn.org/tools/../lib/rpn/proposal_target_layer.py", line 127, in _get_bbox_regression_labels
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
ValueError: could not broadcast input array from shape (4) into shape (0)
```
Can any one give me any suggestion about what to do next?

**Comment by kevin-ssy** [comment]
@liuchang8am Thank you soooooooo much buddy!

**Comment by kevin-ssy** [comment]
@liuchang8am Thank you soooooooo much buddy!

**Comment by monajalal** [comment]
@liuchang8am so there is no pretrained one like there is for pascal_voc for coco? 
I have the same GPU (Tesla K40c), how long the total training took for you?
Can you share the results from your training with me (us)?
