### ISSUE TITLE
Faster rcnn on large images

### ISSUE THREAD

**Issue by dregala3** [rbgirshick/py-faster-rcnn#832]
I noticed that when I run faster rcnn on large images, the algorithm resizes it into smaller dimensions, leading to a deterioration in image quality and failure of the object detect algorithm. More specifically, I noticed that images with dimensions of around 500x700 work really well as the algorithm does not resize them, but anything more than that results in a blurred out resulting test image.

What arguments or parameters do i need to change to prevent this resizing or to allow the algorithm to accept larger test images?

**Comment by vsd550** [comment]
Yeah I am also facing the same problem. If anyone can help us out.
Thanks

**Comment by UsmanMaqbool** [comment]
did you guys find any solution?
