### ISSUE TITLE
Do I need to install caffe in the installation step 4, even if I have already installed caffe?

### ISSUE THREAD

**Issue by hanna-kim** [rbgirshick/py-faster-rcnn#845]
I step four, it says  " 
Build Caffe and pycaffe

cd $FRCN_ROOT/caffe-fast-rcnn
# Now follow the Caffe installation instructions here:
#   http://caffe.berkeleyvision.org/installation.html

# If you're experienced with Caffe and have all of the requirements installed
# and your Makefile.config in place, then simply do:
make -j8 && make pycaffe
"

but I have already installed caffe in home directory.
Should I install caffe again in FRCN_ROOT ?
Or, should I copy caffe directory existing already in the other directory into FRCN_ROOT?

**Comment by minhaj3** [comment]
Hi, I somehow know that this is a stupid question but I am also confused about this. Could you mention what it is that you understood that you closed this issue yourself?

**Comment by hanna-kim** [comment]
@minhaj3 Hi!
 I found out that I have to install caffe again in FRCN_ROOT, since caffe-fast-rcnn is diffrent from original caffe.
