### ISSUE TITLE
GPU memory was no released when running ./tools/demo.py on mutiple images iteratively

### ISSUE THREAD

**Issue by pierrelzw** [rbgirshick/py-faster-rcnn#869]
Hi, I'm trying to use my trained VGG16 model to do inference of thousands of images.  I see that the GPU memory usage  keeps on increasing with time and then the process is killed when GPU memory is not enough. I've tried following code every 100 iterations, but it didn't work. Every time the new net initialized, it requires more GPU memory than the lastest 'net' I delete.  
"""
import gc
del net
gc.colllect()
net = caffe.Net(prototxt, caffemodel, caffe.TEST)
"""
Does anyone have the solution? Thanks!

**Comment by LaiPiXiong** [comment]
Maybe, you can try to change add function in image visualization.

**Comment by pierrelzw** [comment]
> Maybe, you can try to change add function in image visualization.

You‘re right, the problem is the image visualization. The matplotlib opens two many images for drawing and allocates GPU memory without releasing. I solved the problem following https://stackoverflow.com/questions/21884271/warning-about-too-many-open-figures
