### ISSUE TITLE
Losses increase and explode after few iteration

### ISSUE THREAD

**Issue by Walid-Ahmed** [rbgirshick/py-faster-rcnn#895]
I am facing a problem that losses is decreasing at start then start to increase (explode)
I am training using the given code in repo with VGG and VOC2007, I did not change any parameter.

Can you please help?

**Comment by guoqiang0148666** [comment]
How much the iterations?
l train faster rcnn based VGG16 on VOC2007 in 7w iterations reached 69mAP
