### ISSUE TITLE
demo.py in gpu crash and show "Out of memory"

### ISSUE THREAD

**Issue by eternautaCAT** [rbgirshick/py-faster-rcnn#91]
Hi!

I was working with fast RCNN tha last month without any problems. 

This time i decide use faster RCNN. When iI run de demo.py with --cpu flag, every little thing it's all right. But when i run demo.py without any flag (i.e. in gpu mode), i get the following error:

```
F0224 17:36:57.877504 16792 syncedmem.cpp:64] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)
```

I was reading some other issues like this: #2, but the error is still there.

I'm using an AWS server, with a GPU of 4GB.

I read that the error could be because a large batch size, but in this case I'm only running a test in a few smalll images.

Any idea? Could you help me please?

**Comment by eternautaCAT** [comment]
Solved compiling with CUDNN.

**Comment by sarkeribrahim** [comment]
still got this error, i'm using gtx970
shape
I0719 15:09:52.251008  2587 net.cpp:150] Setting up rpn_cls_prob_reshape
I0719 15:09:52.251013  2587 net.cpp:157] Top shape: 1 18 14 14 (3528)
I0719 15:09:52.251016  2587 net.cpp:165] Memory required for data: 116894400
I0719 15:09:52.251019  2587 layer_factory.hpp:77] Creating layer proposal
F0719 15:09:52.251035  2587 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, LRN, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Pooling, Power, ROIPooling, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, SmoothL1Loss, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by melodybinbin** [comment]
@psy770 
Hi,have you solved the problem?I have got the same problem.
I am looking forward to your tips.Thx.

**Comment by melodybinbin** [comment]
Thx.
Just ran into same error, then came across this:
rbgirshick/fast-rcnn#31

You have to uncomment WITH_PYTHON_LAYER := 1 in the Makefile.config, then make clean, then make to rebuild
