### ISSUE TITLE
Error import caffe

### ISSUE THREAD

**Issue by bamontenegro** [rbgirshick/py-faster-rcnn#929]
I made the compilation of caffe and pycaffe without errors, but when I try to import caffe, I have this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.22: cannot open shared object file: No such file or directory
>>>

**Comment by bamontenegro** [comment]
the solution was to run the following command sudo find / -name libprotobuf.so.22, with the address it gives me, add to the path
export LD_LIBRARY_PATH = // home / viia / anaconda2 / pkgs / libprotobuf-3.11.2-hd408876_0 / lib / $ {LD_LIBRARY_PATH: +: $ {LD_LIBRARY_PATH}}.

but now I have this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/viia/py-faster-rcnn/caffe-fast-rcnn/python/caffe/proto/caffe_pb2.py", line 22, in <module>
    07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01'
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

**Comment by BojanAndonovski71** [comment]
have the same error . 

File "/home/admini/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    x10\n\x05scale\x18\x11 \x01(\x02:\x01\x31\x12\x10\n\x08meanfile\x18\x12 \x01(\t\x12\x11\n\tbatchsize\x18\x13 \x01(\r\x12\x13\n\x08\x63ropsize\x18\x14 \x01(\r:\x01\x30\x12\x15\n\x06mirror\x18\x15 \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x05\x62lobs\x18\x32 \x03(\x0b\x32\x10.caffe.BlobProto\x12\x10\n\x08\x62lobs_lr\x18\x33 \x03(\x02\x12\x14\n\x0cweight_decay\x18\x34 \x03(\x02\x12\x14\n\trand_skip\x18\x35 \x01(\r:\x01\x30\x12\x1d\n\x10\x64\x65t_fg_threshold\x18\x36 \x01(\x02:\x03\x30.5\x12\x1d\n\x10\x64\x65t_bg_threshold\x18\x37 \x01(\x02:\x03\x30.5\x12\x1d\n\x0f\x64\x65t_fg_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

Did you fix it?

**Comment by bamontenegro** [comment]
Download caffe_pb2.py from internet and replace the file. It works for me
