### ISSUE TITLE
 Reading dangerously large protocol message.

### ISSUE THREAD

**Issue by rahulsharma11** [rbgirshick/py-faster-rcnn#934]
Hi,
I tried this project in my jetson nano.
Configuration-
RAM-4GB
CUDA-10.0
protobuf - 3.0.0

While using the "tools/demo.py" with default model, i am getting the following error-
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 548317115
I0331 09:47:05.258278 20249 net.cpp:816] Ignoring source layer data
I0331 09:47:05.440400 20249 net.cpp:816] Ignoring source layer drop6
I0331 09:47:05.465526 20249 net.cpp:816] Ignoring source layer drop7
I0331 09:47:05.465593 20249 net.cpp:816] Ignoring source layer fc7_drop7_0_split
I0331 09:47:05.466341 20249 net.cpp:816] Ignoring source layer loss_cls
I0331 09:47:05.466392 20249 net.cpp:816] Ignoring source layer loss_bbox
I0331 09:47:05.470049 20249 net.cpp:816] Ignoring source layer silence_rpn_cls_score
I0331 09:47:05.470110 20249 net.cpp:816] Ignoring source layer silence_rpn_bbox_pred

Loaded network /home/nano2/rahul/orientation-aware-firearm-detection/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel
Killed

Any suggestion?
Thanks

**Comment by rahulsharma11** [comment]
Hi, issue resolved.

**Comment by Blueberry0317** [comment]
excuse me, I meet with a similar problem, may I know the solution?
![1](https://user-images.githubusercontent.com/59813030/112600219-dd371c80-8e4b-11eb-8f60-8ddc674677a5.png)

**Comment by rahulsharma11** [comment]
Hi,
In my case, i was providing wrong prototxt file.

**Comment by Blueberry0317** [comment]
> Hi,
> In my case, i was providing wrong prototxt file.

thank you for your reply and maybe I meet with the 'out of memory' problem, i have changed my device and use tensorflow to train my dataset. thank you all the way.
