### ISSUE TITLE
AssertionError: assert len(top) == len(self._name_to_top_map)

### ISSUE THREAD

**Issue by eternautaCAT** [rbgirshick/py-faster-rcnn#96]
I'm training my own dataset making fine tunning over imageNET.

I have follows some tutorials, and debugged some errors reading discussions in teh issues of teh repo, but there is not any discussion about this error:

`I0226 17:50:22.466792 12885 layer_factory.hpp:77] Creating layer data
I0226 17:50:22.482995 12885 net.cpp:106] Creating Layer data
I0226 17:50:22.483060 12885 net.cpp:411] data -> data
I0226 17:50:22.483094 12885 net.cpp:411] data -> rois
I0226 17:50:22.483120 12885 net.cpp:411] data -> labels
I0226 17:50:22.483144 12885 net.cpp:411] data -> bbox_targets
I0226 17:50:22.483165 12885 net.cpp:411] data -> bbox_inside_weights
I0226 17:50:22.483186 12885 net.cpp:411] data -> bbox_outside_weights
RoiDataLayer: name_to_top: {'gt_boxes': 2, 'data': 0, 'im_info': 1}
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/ubuntu/cars_datasets/privatecars/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/ubuntu/cars_datasets/privatecars/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 43, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
  File "/home/ubuntu/cars_datasets/privatecars/py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 140, in setup
    assert len(top) == len(self._name_to_top_map)
AssertionError
`

The command that i run for trining was:
`./tools/train_net.py --gpu 0 --solver models/VGG_CNN_M_1024/fast_rcnn/solver.prototxt --weights data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel --imdb cars_train --cfg experiments/cfgs/faster_rcnn_end2end.yml`

Thank you!

**Comment by eternautaCAT** [comment]
I was using a wrong proto.txt, sorry.

**Comment by Soda-Wong** [comment]
Hi
I have the same question either.But I think I have the right prototxt.I will preciate it if you can tell me what's wrong with your prototxt.

**Comment by lixiang-ucas** [comment]
Hi @ericromanenghi , i have successfully trained the net my own data using end2end training. However, when training using alternative training, i meet the same error "assert len(top) == len(self._name_to_top_map) AssertionError". Do you have any ideas why this can happen?

**Comment by zhihuiwisdom** [comment]
@lixiang-ucas  I have the same problem, have you sovled it? What is the method?
