### ISSUE TITLE
Error executing forward pass to extract feature after fc7 layer(trained with PASCAL)

### ISSUE THREAD

**Issue by GMNetto** [rbgirshick/py-faster-rcnn#98]
I am trying to execute a python file to extract the features created by the fc7 layer. It basically, recreates the network and runs with some images. I am using the model from models/pascal/VGG16/fast_rcnn/train.prototxt and the caffemodel already trained. However I am having this message.

I0226 23:06:21.890815 12469 layer_factory.hpp:77] Creating layer data
ImportError: No module named roi_data_layer.layer
Traceback (most recent call last):
  File "./create_features.py", line 92, in <module>
    net = caffe.Net(MODEL_FILE, PRETRAINED,caffe.TEST)
SystemError: NULL result without error in PyObject_Call

Does anyone already have this error or knows how to solve it? Looks like it is more a general error to load the pre-trained model and the network structure.

**Comment by gadkins** [comment]
I think this is a simple module visibility issue. Make sure your module roi_data_layer.layer is in your search path. See https://docs.python.org/3/tutorial/modules.html

**Comment by zimenglan-sysu-512** [comment]
@GMNetto have you ever solved this problem?

**Comment by IsSeck** [comment]
I just solve this kind of problem by adding "# coding: utf-8" at the beginning of my code
